<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<RootNamespace>MoAI.App.Workflow</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\infra\MoAI.Infra.Api\MoAI.Infra.Api.csproj" />
		<ProjectReference Include="..\MoAI.App.Workflow.Shared\MoAI.App.Workflow.Shared.csproj" />
	</ItemGroup>

</Project>
