/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AssistantRequestBuilderNavigationMetadata, type AssistantRequestBuilder } from './assistant/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/app
 */
export interface AppRequestBuilder extends BaseRequestBuilder<AppRequestBuilder> {
    /**
     * The assistant property
     */
    get assistant(): AssistantRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AppRequestBuilderUriTemplate = "{+baseurl}/api/app";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AppRequestBuilderNavigationMetadata: Record<Exclude<keyof AppRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    assistant: {
        navigationMetadata: AssistantRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
