<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<RootNamespace>MoAI.Skill</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\database\MoAI.Database.Shared\MoAI.Database.Shared.csproj" />
		<ProjectReference Include="..\..\storage\MoAI.Storage.Shared\MoAI.Storage.Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Commands\" />
		<Folder Include="Models\" />
		<Folder Include="Queries\" />
		<Folder Include="Services\" />
	</ItemGroup>

</Project>
