/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createUserStateInfoFromDiscriminatorValue, type BusinessValidationResult, type UserStateInfo } from '../../../../models/index.js';
// @ts-ignore
import { IsadminRequestBuilderRequestsMetadata, type IsadminRequestBuilder } from './isadmin/index.js';
// @ts-ignore
import { IsdisableRequestBuilderRequestsMetadata, type IsdisableRequestBuilder } from './isdisable/index.js';
// @ts-ignore
import { PasswordRequestBuilderRequestsMetadata, type PasswordRequestBuilder } from './password/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/usermanage/user/{id}
 */
export interface UserItemRequestBuilder extends BaseRequestBuilder<UserItemRequestBuilder> {
    /**
     * The isadmin property
     */
    get isadmin(): IsadminRequestBuilder;
    /**
     * The isdisable property
     */
    get isdisable(): IsdisableRequestBuilder;
    /**
     * The password property
     */
    get password(): PasswordRequestBuilder;
    /**
     * 查询指定用户的信息（仅管理员可访问）.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UserStateInfo>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UserStateInfo | undefined>;
    /**
     * 查询指定用户的信息（仅管理员可访问）.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const UserItemRequestBuilderUriTemplate = "{+baseurl}/api/usermanage/user/{id}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const UserItemRequestBuilderNavigationMetadata: Record<Exclude<keyof UserItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    isadmin: {
        requestsMetadata: IsadminRequestBuilderRequestsMetadata,
    },
    isdisable: {
        requestsMetadata: IsdisableRequestBuilderRequestsMetadata,
    },
    password: {
        requestsMetadata: PasswordRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const UserItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: UserItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUserStateInfoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
