/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createPreUploadWikiDocumentCommandResponseFromDiscriminatorValue, serializePreUploadWikiDocumentCommand, serializePreUploadWikiDocumentCommandResponse, type BusinessValidationResult, type PreUploadWikiDocumentCommand, type PreUploadWikiDocumentCommandResponse } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/wiki/{-id}/documents/preupload
 */
export interface PreuploadRequestBuilder extends BaseRequestBuilder<PreuploadRequestBuilder> {
    /**
     * 预上传知识库文档，仅团队成员可访问.
     * @param body 预上传知识库文档，生成预签名上传地址.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PreUploadWikiDocumentCommandResponse>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     post(body: PreUploadWikiDocumentCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PreUploadWikiDocumentCommandResponse | undefined>;
    /**
     * 预上传知识库文档，仅团队成员可访问.
     * @param body 预上传知识库文档，生成预签名上传地址.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: PreUploadWikiDocumentCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const PreuploadRequestBuilderUriTemplate = "{+baseurl}/api/wiki/{%2Did}/documents/preupload";
/**
 * Metadata for all the requests in the request builder.
 */
export const PreuploadRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: PreuploadRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPreUploadWikiDocumentCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializePreUploadWikiDocumentCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
