/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithTeamItemRequestBuilder, WithTeamItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /aiapi
 */
export interface AiapiRequestBuilder extends BaseRequestBuilder<AiapiRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.aiapi.item collection
     * @param teamId Unique identifier of the item
     * @returns {WithTeamItemRequestBuilder}
     */
     byTeamId(teamId: number) : WithTeamItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AiapiRequestBuilderUriTemplate = "{+baseurl}/aiapi";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AiapiRequestBuilderNavigationMetadata: Record<Exclude<keyof AiapiRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byTeamId: {
        navigationMetadata: WithTeamItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["teamId"],
    },
};
/* tslint:enable */
/* eslint-enable */
