/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type ApiError, type Guid, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * 数据子项.
 */
export interface AuditsInfo extends Parsable {
    /**
     * 创建时间.
     */
    createTime?: string | null;
    /**
     * 创建人ID.
     */
    createUserId?: number | null;
    /**
     * 创建者 名字.
     */
    createUserName?: string | null;
    /**
     * 更新时间.
     */
    updateTime?: string | null;
    /**
     * 更新人ID.
     */
    updateUserId?: number | null;
    /**
     * 更新人 名字.
     */
    updateUserName?: string | null;
}
/**
 * 已绑定的第三方账号信息.
 */
export interface BoundAccountInfo extends Parsable {
    /**
     * 绑定时间.
     */
    createTime?: string | null;
    /**
     * 认证方式图标地址.
     */
    iconUrl?: string | null;
    /**
     * 认证方式名称.
     */
    name?: string | null;
    /**
     * 第三方认证方式 id，对应 OauthConnection 表的 id.
     */
    oAuthId?: Guid | null;
    /**
     * 提供商标识.
     */
    provider?: string | null;
}
/**
 * 错误信息.
 */
export interface BusinessExceptionError extends Parsable {
    /**
     * 错误信息列表.
     */
    errors?: string[] | null;
    /**
     * 名称.
     */
    name?: string | null;
}
/**
 * 错误响应模型.
 */
export interface BusinessValidationResult extends ApiError, Parsable {
    /**
     * 错误码.
     */
    code?: number | null;
    /**
     * 错误消息.
     */
    detail?: string | null;
    /**
     * 具体错误列表.
     */
    errors?: BusinessExceptionError[] | null;
    /**
     * 扩展.
     */
    extensions?: BusinessValidationResult_extensions | null;
    /**
     * 请求上下文 ID.
     */
    requestId?: string | null;
}
/**
 * 扩展.
 */
export interface BusinessValidationResult_extensions extends Parsable {
}
/**
 * 完成文件上传.
 */
export interface CompleteFileUploadCommand extends Parsable {
    /**
     * 文件 ID.
     */
    fileId?: string | null;
    /**
     * 上传成功或失败.
     */
    isSuccess?: boolean | null;
}
/**
 * 完成文件上传响应.
 */
export interface CompleteFileUploadCommandResponse extends Parsable {
    /**
     * 文件公开访问地址（公开文件返回 /static 地址，私有文件为空）.
     */
    accessUrl?: string | null;
    /**
     * 文件 ID.
     */
    fileId?: string | null;
    /**
     * 文件 ObjectKey.
     */
    objectKey?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AuditsInfo}
 */
// @ts-ignore
export function createAuditsInfoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAuditsInfo;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {BoundAccountInfo}
 */
// @ts-ignore
export function createBoundAccountInfoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoBoundAccountInfo;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {BusinessExceptionError}
 */
// @ts-ignore
export function createBusinessExceptionErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoBusinessExceptionError;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {BusinessValidationResult_extensions}
 */
// @ts-ignore
export function createBusinessValidationResult_extensionsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoBusinessValidationResult_extensions;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {BusinessValidationResult}
 */
// @ts-ignore
export function createBusinessValidationResultFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoBusinessValidationResult;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CompleteFileUploadCommand}
 */
// @ts-ignore
export function createCompleteFileUploadCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCompleteFileUploadCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CompleteFileUploadCommandResponse}
 */
// @ts-ignore
export function createCompleteFileUploadCommandResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCompleteFileUploadCommandResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateOAuthConnectionCommand}
 */
// @ts-ignore
export function createCreateOAuthConnectionCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateOAuthConnectionCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {EmptyCommandResponse}
 */
// @ts-ignore
export function createEmptyCommandResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoEmptyCommandResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LoginCommand}
 */
// @ts-ignore
export function createLoginCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLoginCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LoginCommandResponse}
 */
// @ts-ignore
export function createLoginCommandResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLoginCommandResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {OAuthBindExistAccountCommand}
 */
// @ts-ignore
export function createOAuthBindExistAccountCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoOAuthBindExistAccountCommand;
}
/**
 * 创建第三方登录连接配置.
 */
export interface CreateOAuthConnectionCommand extends Parsable {
    /**
     * 图标地址.
     */
    iconUrl?: string | null;
    /**
     * 应用 key.
     */
    key?: string | null;
    /**
     * 认证名称.
     */
    name?: string | null;
    /**
     * 提供商.
     */
    provider?: OAuthPrivider | null;
    /**
     * 密钥.
     */
    secret?: string | null;
    /**
     * 发现端点.
     */
    wellKnown?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {OAuthLoginCommand}
 */
// @ts-ignore
export function createOAuthLoginCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoOAuthLoginCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {OAuthLoginCommandResponse}
 */
// @ts-ignore
export function createOAuthLoginCommandResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoOAuthLoginCommandResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {OAuthRegisterCommand}
 */
// @ts-ignore
export function createOAuthRegisterCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoOAuthRegisterCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PreUploadFileCommandResponse}
 */
// @ts-ignore
export function createPreUploadFileCommandResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPreUploadFileCommandResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PreUploadImageCommand}
 */
// @ts-ignore
export function createPreUploadImageCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPreUploadImageCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PreUploadTempFileCommand}
 */
// @ts-ignore
export function createPreUploadTempFileCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPreUploadTempFileCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {QueryAllOAuthConnectionCommandResponse}
 */
// @ts-ignore
export function createQueryAllOAuthConnectionCommandResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoQueryAllOAuthConnectionCommandResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {QueryAllOAuthConnectionCommandResponseItem}
 */
// @ts-ignore
export function createQueryAllOAuthConnectionCommandResponseItemFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoQueryAllOAuthConnectionCommandResponseItem;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {QueryAllOAuthPrividerCommandResponse}
 */
// @ts-ignore
export function createQueryAllOAuthPrividerCommandResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoQueryAllOAuthPrividerCommandResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {QueryAllOAuthPrividerCommandResponseItem}
 */
// @ts-ignore
export function createQueryAllOAuthPrividerCommandResponseItemFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoQueryAllOAuthPrividerCommandResponseItem;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {QueryServerInfoCommandResponse}
 */
// @ts-ignore
export function createQueryServerInfoCommandResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoQueryServerInfoCommandResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {QuerySettingsCommandResponse}
 */
// @ts-ignore
export function createQuerySettingsCommandResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoQuerySettingsCommandResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {QueryUserBoundAccountsCommandResponse}
 */
// @ts-ignore
export function createQueryUserBoundAccountsCommandResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoQueryUserBoundAccountsCommandResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RefreshTokenCommand}
 */
// @ts-ignore
export function createRefreshTokenCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRefreshTokenCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RefreshTokenCommandResponse}
 */
// @ts-ignore
export function createRefreshTokenCommandResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRefreshTokenCommandResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RegisterUserCommand}
 */
// @ts-ignore
export function createRegisterUserCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRegisterUserCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ResetPasswordCommand}
 */
// @ts-ignore
export function createResetPasswordCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoResetPasswordCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SaveSettingCommand}
 */
// @ts-ignore
export function createSaveSettingCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSaveSettingCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SettingItemResponse}
 */
// @ts-ignore
export function createSettingItemResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSettingItemResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SimpleGuid}
 */
// @ts-ignore
export function createSimpleGuidFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSimpleGuid;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SimpleLong}
 */
// @ts-ignore
export function createSimpleLongFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSimpleLong;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SimpleOfGuid}
 */
// @ts-ignore
export function createSimpleOfGuidFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSimpleOfGuid;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SimpleOfLong}
 */
// @ts-ignore
export function createSimpleOfLongFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSimpleOfLong;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UnbindUserOAuthCommand}
 */
// @ts-ignore
export function createUnbindUserOAuthCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUnbindUserOAuthCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdateOAuthConnectionCommand}
 */
// @ts-ignore
export function createUpdateOAuthConnectionCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdateOAuthConnectionCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdateUserAvatarCommand}
 */
// @ts-ignore
export function createUpdateUserAvatarCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdateUserAvatarCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdateUserInfoCommand}
 */
// @ts-ignore
export function createUpdateUserInfoCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdateUserInfoCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UserStateInfo}
 */
// @ts-ignore
export function createUserStateInfoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUserStateInfo;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAuditsInfo(auditsInfo: Partial<AuditsInfo> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "createTime": n => { auditsInfo.createTime = n.getStringValue(); },
        "createUserId": n => { auditsInfo.createUserId = n.getNumberValue(); },
        "createUserName": n => { auditsInfo.createUserName = n.getStringValue(); },
        "updateTime": n => { auditsInfo.updateTime = n.getStringValue(); },
        "updateUserId": n => { auditsInfo.updateUserId = n.getNumberValue(); },
        "updateUserName": n => { auditsInfo.updateUserName = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoBoundAccountInfo(boundAccountInfo: Partial<BoundAccountInfo> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "createTime": n => { boundAccountInfo.createTime = n.getStringValue(); },
        "iconUrl": n => { boundAccountInfo.iconUrl = n.getStringValue(); },
        "name": n => { boundAccountInfo.name = n.getStringValue(); },
        "oAuthId": n => { boundAccountInfo.oAuthId = n.getGuidValue(); },
        "provider": n => { boundAccountInfo.provider = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoBusinessExceptionError(businessExceptionError: Partial<BusinessExceptionError> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "errors": n => { businessExceptionError.errors = n.getCollectionOfPrimitiveValues<string>(); },
        "name": n => { businessExceptionError.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoBusinessValidationResult(businessValidationResult: Partial<BusinessValidationResult> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { businessValidationResult.code = n.getNumberValue(); },
        "detail": n => { businessValidationResult.detail = n.getStringValue(); },
        "errors": n => { businessValidationResult.errors = n.getCollectionOfObjectValues<BusinessExceptionError>(createBusinessExceptionErrorFromDiscriminatorValue); },
        "extensions": n => { businessValidationResult.extensions = n.getObjectValue<BusinessValidationResult_extensions>(createBusinessValidationResult_extensionsFromDiscriminatorValue); },
        "requestId": n => { businessValidationResult.requestId = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoBusinessValidationResult_extensions(businessValidationResult_extensions: Partial<BusinessValidationResult_extensions> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCompleteFileUploadCommand(completeFileUploadCommand: Partial<CompleteFileUploadCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "fileId": n => { completeFileUploadCommand.fileId = n.getStringValue(); },
        "isSuccess": n => { completeFileUploadCommand.isSuccess = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCompleteFileUploadCommandResponse(completeFileUploadCommandResponse: Partial<CompleteFileUploadCommandResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "accessUrl": n => { completeFileUploadCommandResponse.accessUrl = n.getStringValue(); },
        "fileId": n => { completeFileUploadCommandResponse.fileId = n.getStringValue(); },
        "objectKey": n => { completeFileUploadCommandResponse.objectKey = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateOAuthConnectionCommand(createOAuthConnectionCommand: Partial<CreateOAuthConnectionCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "iconUrl": n => { createOAuthConnectionCommand.iconUrl = n.getStringValue(); },
        "key": n => { createOAuthConnectionCommand.key = n.getStringValue(); },
        "name": n => { createOAuthConnectionCommand.name = n.getStringValue(); },
        "provider": n => { createOAuthConnectionCommand.provider = n.getEnumValue<OAuthPrivider>(OAuthPrividerObject); },
        "secret": n => { createOAuthConnectionCommand.secret = n.getStringValue(); },
        "wellKnown": n => { createOAuthConnectionCommand.wellKnown = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoEmptyCommandResponse(emptyCommandResponse: Partial<EmptyCommandResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLoginCommand(loginCommand: Partial<LoginCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "password": n => { loginCommand.password = n.getStringValue(); },
        "userName": n => { loginCommand.userName = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLoginCommandResponse(loginCommandResponse: Partial<LoginCommandResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "accessToken": n => { loginCommandResponse.accessToken = n.getStringValue(); },
        "expiresIn": n => { loginCommandResponse.expiresIn = n.getStringValue(); },
        "refreshToken": n => { loginCommandResponse.refreshToken = n.getStringValue(); },
        "tokenType": n => { loginCommandResponse.tokenType = n.getStringValue(); },
        "userId": n => { loginCommandResponse.userId = n.getStringValue(); },
        "userName": n => { loginCommandResponse.userName = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoOAuthBindExistAccountCommand(oAuthBindExistAccountCommand: Partial<OAuthBindExistAccountCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "tempOAuthBindId": n => { oAuthBindExistAccountCommand.tempOAuthBindId = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoOAuthLoginCommand(oAuthLoginCommand: Partial<OAuthLoginCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { oAuthLoginCommand.code = n.getStringValue(); },
        "oAuthId": n => { oAuthLoginCommand.oAuthId = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoOAuthLoginCommandResponse(oAuthLoginCommandResponse: Partial<OAuthLoginCommandResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "isBindUser": n => { oAuthLoginCommandResponse.isBindUser = n.getBooleanValue(); },
        "loginCommandResponse": n => { oAuthLoginCommandResponse.loginCommandResponse = n.getObjectValue<LoginCommandResponse>(createLoginCommandResponseFromDiscriminatorValue); },
        "name": n => { oAuthLoginCommandResponse.name = n.getStringValue(); },
        "oAuthId": n => { oAuthLoginCommandResponse.oAuthId = n.getGuidValue(); },
        "tempOAuthBindId": n => { oAuthLoginCommandResponse.tempOAuthBindId = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoOAuthRegisterCommand(oAuthRegisterCommand: Partial<OAuthRegisterCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "tempOAuthBindId": n => { oAuthRegisterCommand.tempOAuthBindId = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPreUploadFileCommandResponse(preUploadFileCommandResponse: Partial<PreUploadFileCommandResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "expiration": n => { preUploadFileCommandResponse.expiration = n.getStringValue(); },
        "fileId": n => { preUploadFileCommandResponse.fileId = n.getStringValue(); },
        "isExist": n => { preUploadFileCommandResponse.isExist = n.getBooleanValue(); },
        "objectKey": n => { preUploadFileCommandResponse.objectKey = n.getStringValue(); },
        "uploadUrl": n => { preUploadFileCommandResponse.uploadUrl = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPreUploadImageCommand(preUploadImageCommand: Partial<PreUploadImageCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "contentType": n => { preUploadImageCommand.contentType = n.getStringValue(); },
        "fileName": n => { preUploadImageCommand.fileName = n.getStringValue(); },
        "fileSize": n => { preUploadImageCommand.fileSize = n.getNumberValue(); },
        "shA256": n => { preUploadImageCommand.shA256 = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPreUploadTempFileCommand(preUploadTempFileCommand: Partial<PreUploadTempFileCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "contentType": n => { preUploadTempFileCommand.contentType = n.getStringValue(); },
        "fileName": n => { preUploadTempFileCommand.fileName = n.getStringValue(); },
        "fileSize": n => { preUploadTempFileCommand.fileSize = n.getNumberValue(); },
        "shA256": n => { preUploadTempFileCommand.shA256 = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoQueryAllOAuthConnectionCommandResponse(queryAllOAuthConnectionCommandResponse: Partial<QueryAllOAuthConnectionCommandResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "items": n => { queryAllOAuthConnectionCommandResponse.items = n.getCollectionOfObjectValues<QueryAllOAuthConnectionCommandResponseItem>(createQueryAllOAuthConnectionCommandResponseItemFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoQueryAllOAuthConnectionCommandResponseItem(queryAllOAuthConnectionCommandResponseItem: Partial<QueryAllOAuthConnectionCommandResponseItem> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoAuditsInfo(queryAllOAuthConnectionCommandResponseItem),
        "authorizeUrl": n => { queryAllOAuthConnectionCommandResponseItem.authorizeUrl = n.getStringValue(); },
        "iconUrl": n => { queryAllOAuthConnectionCommandResponseItem.iconUrl = n.getStringValue(); },
        "id": n => { queryAllOAuthConnectionCommandResponseItem.id = n.getGuidValue(); },
        "key": n => { queryAllOAuthConnectionCommandResponseItem.key = n.getStringValue(); },
        "name": n => { queryAllOAuthConnectionCommandResponseItem.name = n.getStringValue(); },
        "provider": n => { queryAllOAuthConnectionCommandResponseItem.provider = n.getStringValue(); },
        "wellKnown": n => { queryAllOAuthConnectionCommandResponseItem.wellKnown = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoQueryAllOAuthPrividerCommandResponse(queryAllOAuthPrividerCommandResponse: Partial<QueryAllOAuthPrividerCommandResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "items": n => { queryAllOAuthPrividerCommandResponse.items = n.getCollectionOfObjectValues<QueryAllOAuthPrividerCommandResponseItem>(createQueryAllOAuthPrividerCommandResponseItemFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoQueryAllOAuthPrividerCommandResponseItem(queryAllOAuthPrividerCommandResponseItem: Partial<QueryAllOAuthPrividerCommandResponseItem> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "iconUrl": n => { queryAllOAuthPrividerCommandResponseItem.iconUrl = n.getStringValue(); },
        "name": n => { queryAllOAuthPrividerCommandResponseItem.name = n.getStringValue(); },
        "oAuthId": n => { queryAllOAuthPrividerCommandResponseItem.oAuthId = n.getGuidValue(); },
        "provider": n => { queryAllOAuthPrividerCommandResponseItem.provider = n.getStringValue(); },
        "redirectUrl": n => { queryAllOAuthPrividerCommandResponseItem.redirectUrl = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoQueryServerInfoCommandResponse(queryServerInfoCommandResponse: Partial<QueryServerInfoCommandResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "maxUploadFileSize": n => { queryServerInfoCommandResponse.maxUploadFileSize = n.getNumberValue(); },
        "name": n => { queryServerInfoCommandResponse.name = n.getStringValue(); },
        "publicStoreUrl": n => { queryServerInfoCommandResponse.publicStoreUrl = n.getStringValue(); },
        "rsaPublic": n => { queryServerInfoCommandResponse.rsaPublic = n.getStringValue(); },
        "serviceUrl": n => { queryServerInfoCommandResponse.serviceUrl = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoQuerySettingsCommandResponse(querySettingsCommandResponse: Partial<QuerySettingsCommandResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "items": n => { querySettingsCommandResponse.items = n.getCollectionOfObjectValues<SettingItemResponse>(createSettingItemResponseFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoQueryUserBoundAccountsCommandResponse(queryUserBoundAccountsCommandResponse: Partial<QueryUserBoundAccountsCommandResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "items": n => { queryUserBoundAccountsCommandResponse.items = n.getCollectionOfObjectValues<BoundAccountInfo>(createBoundAccountInfoFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRefreshTokenCommand(refreshTokenCommand: Partial<RefreshTokenCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "refreshToken": n => { refreshTokenCommand.refreshToken = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRefreshTokenCommandResponse(refreshTokenCommandResponse: Partial<RefreshTokenCommandResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "accessToken": n => { refreshTokenCommandResponse.accessToken = n.getStringValue(); },
        "expiresIn": n => { refreshTokenCommandResponse.expiresIn = n.getStringValue(); },
        "refreshToken": n => { refreshTokenCommandResponse.refreshToken = n.getStringValue(); },
        "tokenType": n => { refreshTokenCommandResponse.tokenType = n.getStringValue(); },
        "userId": n => { refreshTokenCommandResponse.userId = n.getStringValue(); },
        "userName": n => { refreshTokenCommandResponse.userName = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRegisterUserCommand(registerUserCommand: Partial<RegisterUserCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { registerUserCommand.email = n.getStringValue(); },
        "nickName": n => { registerUserCommand.nickName = n.getStringValue(); },
        "password": n => { registerUserCommand.password = n.getStringValue(); },
        "phone": n => { registerUserCommand.phone = n.getStringValue(); },
        "userName": n => { registerUserCommand.userName = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoResetPasswordCommand(resetPasswordCommand: Partial<ResetPasswordCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "contextUserId": n => { resetPasswordCommand.contextUserId = n.getStringValue(); },
        "contextUserType": n => { resetPasswordCommand.contextUserType = n.getEnumValue<UserType>(UserTypeObject); },
        "newPassword": n => { resetPasswordCommand.newPassword = n.getStringValue(); },
        "oldPassword": n => { resetPasswordCommand.oldPassword = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSaveSettingCommand(saveSettingCommand: Partial<SaveSettingCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "key": n => { saveSettingCommand.key = n.getStringValue(); },
        "value": n => { saveSettingCommand.value = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSettingItemResponse(settingItemResponse: Partial<SettingItemResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "description": n => { settingItemResponse.description = n.getStringValue(); },
        "key": n => { settingItemResponse.key = n.getStringValue(); },
        "name": n => { settingItemResponse.name = n.getStringValue(); },
        "value": n => { settingItemResponse.value = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSimpleGuid(simpleGuid: Partial<SimpleGuid> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoSimpleOfGuid(simpleGuid),
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSimpleLong(simpleLong: Partial<SimpleLong> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoSimpleOfLong(simpleLong),
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSimpleOfGuid(simpleOfGuid: Partial<SimpleOfGuid> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "value": n => { simpleOfGuid.value = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSimpleOfLong(simpleOfLong: Partial<SimpleOfLong> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "value": n => { simpleOfLong.value = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUnbindUserOAuthCommand(unbindUserOAuthCommand: Partial<UnbindUserOAuthCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "contextUserId": n => { unbindUserOAuthCommand.contextUserId = n.getStringValue(); },
        "contextUserType": n => { unbindUserOAuthCommand.contextUserType = n.getEnumValue<UserType>(UserTypeObject); },
        "providerId": n => { unbindUserOAuthCommand.providerId = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdateOAuthConnectionCommand(updateOAuthConnectionCommand: Partial<UpdateOAuthConnectionCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "iconUrl": n => { updateOAuthConnectionCommand.iconUrl = n.getStringValue(); },
        "key": n => { updateOAuthConnectionCommand.key = n.getStringValue(); },
        "name": n => { updateOAuthConnectionCommand.name = n.getStringValue(); },
        "oAuthConnectionId": n => { updateOAuthConnectionCommand.oAuthConnectionId = n.getGuidValue(); },
        "provider": n => { updateOAuthConnectionCommand.provider = n.getEnumValue<OAuthPrivider>(OAuthPrividerObject); },
        "secret": n => { updateOAuthConnectionCommand.secret = n.getStringValue(); },
        "wellKnown": n => { updateOAuthConnectionCommand.wellKnown = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdateUserAvatarCommand(updateUserAvatarCommand: Partial<UpdateUserAvatarCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "contextUserId": n => { updateUserAvatarCommand.contextUserId = n.getStringValue(); },
        "contextUserType": n => { updateUserAvatarCommand.contextUserType = n.getEnumValue<UserType>(UserTypeObject); },
        "objectKey": n => { updateUserAvatarCommand.objectKey = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdateUserInfoCommand(updateUserInfoCommand: Partial<UpdateUserInfoCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "contextUserId": n => { updateUserInfoCommand.contextUserId = n.getStringValue(); },
        "contextUserType": n => { updateUserInfoCommand.contextUserType = n.getEnumValue<UserType>(UserTypeObject); },
        "nickName": n => { updateUserInfoCommand.nickName = n.getStringValue(); },
        "phone": n => { updateUserInfoCommand.phone = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUserStateInfo(userStateInfo: Partial<UserStateInfo> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "avatar": n => { userStateInfo.avatar = n.getStringValue(); },
        "email": n => { userStateInfo.email = n.getStringValue(); },
        "isAdmin": n => { userStateInfo.isAdmin = n.getBooleanValue(); },
        "isDeleted": n => { userStateInfo.isDeleted = n.getBooleanValue(); },
        "isDisable": n => { userStateInfo.isDisable = n.getBooleanValue(); },
        "isRoot": n => { userStateInfo.isRoot = n.getBooleanValue(); },
        "nickName": n => { userStateInfo.nickName = n.getStringValue(); },
        "phone": n => { userStateInfo.phone = n.getStringValue(); },
        "userId": n => { userStateInfo.userId = n.getStringValue(); },
        "userName": n => { userStateInfo.userName = n.getStringValue(); },
    }
}
/**
 * 空数据.
 */
export interface EmptyCommandResponse extends Parsable {
}
/**
 * 登录.
 */
export interface LoginCommand extends Parsable {
    /**
     * 密码，使用 RSA 公钥加密.
     */
    password?: string | null;
    /**
     * 用户名或邮箱.
     */
    userName?: string | null;
}
/**
 * 登录结果.
 */
export interface LoginCommandResponse extends Parsable {
    /**
     * 访问令牌.
     */
    accessToken?: string | null;
    /**
     * 过期时间（秒）.
     */
    expiresIn?: string | null;
    /**
     * 刷新令牌.
     */
    refreshToken?: string | null;
    /**
     * 令牌类型.
     */
    tokenType?: string | null;
    /**
     * 用户ID.
     */
    userId?: string | null;
    /**
     * 用户名.
     */
    userName?: string | null;
}
/**
 * 使用 OAuth 绑定已存在的账号.
 */
export interface OAuthBindExistAccountCommand extends Parsable {
    /**
     * id.
     */
    tempOAuthBindId?: Guid | null;
}
/**
 * 使用 OAuth 登录，用于第三方登录回调后触发接口.
 */
export interface OAuthLoginCommand extends Parsable {
    /**
     * Code.
     */
    code?: string | null;
    /**
     * id.
     */
    oAuthId?: Guid | null;
}
/**
 * 响应.
 */
export interface OAuthLoginCommandResponse extends Parsable {
    /**
     * 如果已经绑定用户.
     */
    isBindUser?: boolean | null;
    /**
     * IsBindUser == true 时，返回用户登录信息.
     */
    loginCommandResponse?: LoginCommandResponse | null;
    /**
     * 用户在第三方登录的名字.
     */
    name?: string | null;
    /**
     * id.
     */
    oAuthId?: Guid | null;
    /**
     * 如果此 id 没有绑定过用户，则返回此 id，使用此 id 绑定或注册用户.
     */
    tempOAuthBindId?: Guid | null;
}
export type OAuthPrivider = (typeof OAuthPrividerObject)[keyof typeof OAuthPrividerObject];
/**
 * 第三方账号没有绑定记录时，使用第三方账号一键注册.
 */
export interface OAuthRegisterCommand extends Parsable {
    /**
     * 登录绑定 OAuth 用户 ID.
     */
    tempOAuthBindId?: Guid | null;
}
/**
 * 文件预上传响应.
 */
export interface PreUploadFileCommandResponse extends Parsable {
    /**
     * 签名过期时间，当 IsExist = true 时为空.
     */
    expiration?: string | null;
    /**
     * 文件 ID.
     */
    fileId?: string | null;
    /**
     * 文件是否已存在，如已存在则无需再次上传.
     */
    isExist?: boolean | null;
    /**
     * 文件 ObjectKey.
     */
    objectKey?: string | null;
    /**
     * 预签名上传地址，当 IsExist = true 时为空.
     */
    uploadUrl?: string | null;
}
/**
 * 图片预上传命令，生成预签名上传地址.
 */
export interface PreUploadImageCommand extends Parsable {
    /**
     * 文件类型 (MIME Type).
     */
    contentType?: string | null;
    /**
     * 文件名称.
     */
    fileName?: string | null;
    /**
     * 文件大小 (字节).
     */
    fileSize?: number | null;
    /**
     * 文件 SHA-256.
     */
    shA256?: string | null;
}
/**
 * 临时文件预上传命令，生成预签名上传地址.
 */
export interface PreUploadTempFileCommand extends Parsable {
    /**
     * 文件类型 (MIME Type).
     */
    contentType?: string | null;
    /**
     * 文件名称.
     */
    fileName?: string | null;
    /**
     * 文件大小 (字节).
     */
    fileSize?: number | null;
    /**
     * 文件 SHA-256.
     */
    shA256?: string | null;
}
/**
 * QueryAllOAuthConnectionCommandResponse.
 */
export interface QueryAllOAuthConnectionCommandResponse extends Parsable {
    /**
     * 集合.
     */
    items?: QueryAllOAuthConnectionCommandResponseItem[] | null;
}
/**
 * QueryAllOAuthConnectionCommandResponseItem.
 */
export interface QueryAllOAuthConnectionCommandResponseItem extends AuditsInfo, Parsable {
    /**
     * 登录跳转地址.
     */
    authorizeUrl?: string | null;
    /**
     * 图标地址.
     */
    iconUrl?: string | null;
    /**
     * id.
     */
    id?: Guid | null;
    /**
     * 应用 key.
     */
    key?: string | null;
    /**
     * 认证名称.
     */
    name?: string | null;
    /**
     * 提供商标识.
     */
    provider?: string | null;
    /**
     * 发现端点.
     */
    wellKnown?: string | null;
}
/**
 * QueryAllOAuthPrividerCommandResponse。
 */
export interface QueryAllOAuthPrividerCommandResponse extends Parsable {
    /**
     * 集合.
     */
    items?: QueryAllOAuthPrividerCommandResponseItem[] | null;
}
/**
 * QueryAllOAuthPrividerCommandResponseItem.
 */
export interface QueryAllOAuthPrividerCommandResponseItem extends Parsable {
    /**
     * 提供商图标地址
     */
    iconUrl?: string | null;
    /**
     * 提供商名称
     */
    name?: string | null;
    /**
     * id.
     */
    oAuthId?: Guid | null;
    /**
     * 提供商标识
     */
    provider?: string | null;
    /**
     * 授权地址.
     */
    redirectUrl?: string | null;
}
/**
 * 服务器信息.
 */
export interface QueryServerInfoCommandResponse extends Parsable {
    /**
     * 最大可上传文件大小，单位为字节.
     */
    maxUploadFileSize?: number | null;
    /**
     * 网站名称.
     */
    name?: string | null;
    /**
     * 公共存储地址，静态资源时可直接访问.
     */
    publicStoreUrl?: string | null;
    /**
     * RSA 公钥，用于加密密码等信息传输到服务器.
     */
    rsaPublic?: string | null;
    /**
     * 系统访问地址.
     */
    serviceUrl?: string | null;
}
/**
 * 查询设置项响应.
 */
export interface QuerySettingsCommandResponse extends Parsable {
    /**
     * 设置项集合.
     */
    items?: SettingItemResponse[] | null;
}
/**
 * 查询当前用户已绑定第三方账号的响应.
 */
export interface QueryUserBoundAccountsCommandResponse extends Parsable {
    /**
     * 已绑定的第三方账号集合.
     */
    items?: BoundAccountInfo[] | null;
}
/**
 * 刷新 token.
 */
export interface RefreshTokenCommand extends Parsable {
    /**
     * 刷新令牌.
     */
    refreshToken?: string | null;
}
/**
 * RefreshTokenCommandResponse.
 */
export interface RefreshTokenCommandResponse extends Parsable {
    /**
     * 访问令牌.
     */
    accessToken?: string | null;
    /**
     * 过期时间（秒）.
     */
    expiresIn?: string | null;
    /**
     * 刷新令牌.
     */
    refreshToken?: string | null;
    /**
     * 令牌类型.
     */
    tokenType?: string | null;
    /**
     * 用户ID.
     */
    userId?: string | null;
    /**
     * 用户名.
     */
    userName?: string | null;
}
/**
 * 注册用户.
 */
export interface RegisterUserCommand extends Parsable {
    /**
     * 邮箱.
     */
    email?: string | null;
    /**
     * 昵称.
     */
    nickName?: string | null;
    /**
     * 密码，接口请求时，使用 RSA 公钥加密密码.
     */
    password?: string | null;
    /**
     * 手机号.
     */
    phone?: string | null;
    /**
     * 用户名.
     */
    userName?: string | null;
}
/**
 * 重置用户密码.
 */
export interface ResetPasswordCommand extends Parsable {
    /**
     * 通过上下文自动配置id，前端不需要传递.
     */
    contextUserId?: string | null;
    /**
     * 通过上下文自动配置用户了偶像，前端不需要传递.
     */
    contextUserType?: UserType | null;
    /**
     * 新密码，使用 RSA 公钥加密.
     */
    newPassword?: string | null;
    /**
     * 原密码，使用 RSA 公钥加密.
     */
    oldPassword?: string | null;
}
/**
 * 保存设置.
 */
export interface SaveSettingCommand extends Parsable {
    /**
     * 设置项 key.
     */
    key?: string | null;
    /**
     * 设置项值.
     */
    value?: string | null;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAuditsInfo(writer: SerializationWriter, auditsInfo: Partial<AuditsInfo> | undefined | null = {}) : void {
    if (auditsInfo) {
        writer.writeStringValue("createTime", auditsInfo.createTime);
        writer.writeNumberValue("createUserId", auditsInfo.createUserId);
        writer.writeStringValue("createUserName", auditsInfo.createUserName);
        writer.writeStringValue("updateTime", auditsInfo.updateTime);
        writer.writeNumberValue("updateUserId", auditsInfo.updateUserId);
        writer.writeStringValue("updateUserName", auditsInfo.updateUserName);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeBoundAccountInfo(writer: SerializationWriter, boundAccountInfo: Partial<BoundAccountInfo> | undefined | null = {}) : void {
    if (boundAccountInfo) {
        writer.writeStringValue("createTime", boundAccountInfo.createTime);
        writer.writeStringValue("iconUrl", boundAccountInfo.iconUrl);
        writer.writeStringValue("name", boundAccountInfo.name);
        writer.writeGuidValue("oAuthId", boundAccountInfo.oAuthId);
        writer.writeStringValue("provider", boundAccountInfo.provider);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeBusinessExceptionError(writer: SerializationWriter, businessExceptionError: Partial<BusinessExceptionError> | undefined | null = {}) : void {
    if (businessExceptionError) {
        writer.writeCollectionOfPrimitiveValues<string>("errors", businessExceptionError.errors);
        writer.writeStringValue("name", businessExceptionError.name);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeBusinessValidationResult(writer: SerializationWriter, businessValidationResult: Partial<BusinessValidationResult> | undefined | null = {}) : void {
    if (businessValidationResult) {
        writer.writeNumberValue("code", businessValidationResult.code);
        writer.writeStringValue("detail", businessValidationResult.detail);
        writer.writeCollectionOfObjectValues<BusinessExceptionError>("errors", businessValidationResult.errors, serializeBusinessExceptionError);
        writer.writeObjectValue<BusinessValidationResult_extensions>("extensions", businessValidationResult.extensions, serializeBusinessValidationResult_extensions);
        writer.writeStringValue("requestId", businessValidationResult.requestId);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeBusinessValidationResult_extensions(writer: SerializationWriter, businessValidationResult_extensions: Partial<BusinessValidationResult_extensions> | undefined | null = {}) : void {
    if (businessValidationResult_extensions) {
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCompleteFileUploadCommand(writer: SerializationWriter, completeFileUploadCommand: Partial<CompleteFileUploadCommand> | undefined | null = {}) : void {
    if (completeFileUploadCommand) {
        writer.writeStringValue("fileId", completeFileUploadCommand.fileId);
        writer.writeBooleanValue("isSuccess", completeFileUploadCommand.isSuccess);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCompleteFileUploadCommandResponse(writer: SerializationWriter, completeFileUploadCommandResponse: Partial<CompleteFileUploadCommandResponse> | undefined | null = {}) : void {
    if (completeFileUploadCommandResponse) {
        writer.writeStringValue("accessUrl", completeFileUploadCommandResponse.accessUrl);
        writer.writeStringValue("fileId", completeFileUploadCommandResponse.fileId);
        writer.writeStringValue("objectKey", completeFileUploadCommandResponse.objectKey);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateOAuthConnectionCommand(writer: SerializationWriter, createOAuthConnectionCommand: Partial<CreateOAuthConnectionCommand> | undefined | null = {}) : void {
    if (createOAuthConnectionCommand) {
        writer.writeStringValue("iconUrl", createOAuthConnectionCommand.iconUrl);
        writer.writeStringValue("key", createOAuthConnectionCommand.key);
        writer.writeStringValue("name", createOAuthConnectionCommand.name);
        writer.writeEnumValue<OAuthPrivider>("provider", createOAuthConnectionCommand.provider);
        writer.writeStringValue("secret", createOAuthConnectionCommand.secret);
        writer.writeStringValue("wellKnown", createOAuthConnectionCommand.wellKnown);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeEmptyCommandResponse(writer: SerializationWriter, emptyCommandResponse: Partial<EmptyCommandResponse> | undefined | null = {}) : void {
    if (emptyCommandResponse) {
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLoginCommand(writer: SerializationWriter, loginCommand: Partial<LoginCommand> | undefined | null = {}) : void {
    if (loginCommand) {
        writer.writeStringValue("password", loginCommand.password);
        writer.writeStringValue("userName", loginCommand.userName);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLoginCommandResponse(writer: SerializationWriter, loginCommandResponse: Partial<LoginCommandResponse> | undefined | null = {}) : void {
    if (loginCommandResponse) {
        writer.writeStringValue("accessToken", loginCommandResponse.accessToken);
        writer.writeStringValue("expiresIn", loginCommandResponse.expiresIn);
        writer.writeStringValue("refreshToken", loginCommandResponse.refreshToken);
        writer.writeStringValue("tokenType", loginCommandResponse.tokenType);
        writer.writeStringValue("userId", loginCommandResponse.userId);
        writer.writeStringValue("userName", loginCommandResponse.userName);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeOAuthBindExistAccountCommand(writer: SerializationWriter, oAuthBindExistAccountCommand: Partial<OAuthBindExistAccountCommand> | undefined | null = {}) : void {
    if (oAuthBindExistAccountCommand) {
        writer.writeGuidValue("tempOAuthBindId", oAuthBindExistAccountCommand.tempOAuthBindId);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeOAuthLoginCommand(writer: SerializationWriter, oAuthLoginCommand: Partial<OAuthLoginCommand> | undefined | null = {}) : void {
    if (oAuthLoginCommand) {
        writer.writeStringValue("code", oAuthLoginCommand.code);
        writer.writeGuidValue("oAuthId", oAuthLoginCommand.oAuthId);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeOAuthLoginCommandResponse(writer: SerializationWriter, oAuthLoginCommandResponse: Partial<OAuthLoginCommandResponse> | undefined | null = {}) : void {
    if (oAuthLoginCommandResponse) {
        writer.writeBooleanValue("isBindUser", oAuthLoginCommandResponse.isBindUser);
        writer.writeObjectValue<LoginCommandResponse>("loginCommandResponse", oAuthLoginCommandResponse.loginCommandResponse, serializeLoginCommandResponse);
        writer.writeStringValue("name", oAuthLoginCommandResponse.name);
        writer.writeGuidValue("oAuthId", oAuthLoginCommandResponse.oAuthId);
        writer.writeGuidValue("tempOAuthBindId", oAuthLoginCommandResponse.tempOAuthBindId);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeOAuthRegisterCommand(writer: SerializationWriter, oAuthRegisterCommand: Partial<OAuthRegisterCommand> | undefined | null = {}) : void {
    if (oAuthRegisterCommand) {
        writer.writeGuidValue("tempOAuthBindId", oAuthRegisterCommand.tempOAuthBindId);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePreUploadFileCommandResponse(writer: SerializationWriter, preUploadFileCommandResponse: Partial<PreUploadFileCommandResponse> | undefined | null = {}) : void {
    if (preUploadFileCommandResponse) {
        writer.writeStringValue("expiration", preUploadFileCommandResponse.expiration);
        writer.writeStringValue("fileId", preUploadFileCommandResponse.fileId);
        writer.writeBooleanValue("isExist", preUploadFileCommandResponse.isExist);
        writer.writeStringValue("objectKey", preUploadFileCommandResponse.objectKey);
        writer.writeStringValue("uploadUrl", preUploadFileCommandResponse.uploadUrl);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePreUploadImageCommand(writer: SerializationWriter, preUploadImageCommand: Partial<PreUploadImageCommand> | undefined | null = {}) : void {
    if (preUploadImageCommand) {
        writer.writeStringValue("contentType", preUploadImageCommand.contentType);
        writer.writeStringValue("fileName", preUploadImageCommand.fileName);
        writer.writeNumberValue("fileSize", preUploadImageCommand.fileSize);
        writer.writeStringValue("shA256", preUploadImageCommand.shA256);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePreUploadTempFileCommand(writer: SerializationWriter, preUploadTempFileCommand: Partial<PreUploadTempFileCommand> | undefined | null = {}) : void {
    if (preUploadTempFileCommand) {
        writer.writeStringValue("contentType", preUploadTempFileCommand.contentType);
        writer.writeStringValue("fileName", preUploadTempFileCommand.fileName);
        writer.writeNumberValue("fileSize", preUploadTempFileCommand.fileSize);
        writer.writeStringValue("shA256", preUploadTempFileCommand.shA256);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeQueryAllOAuthConnectionCommandResponse(writer: SerializationWriter, queryAllOAuthConnectionCommandResponse: Partial<QueryAllOAuthConnectionCommandResponse> | undefined | null = {}) : void {
    if (queryAllOAuthConnectionCommandResponse) {
        writer.writeCollectionOfObjectValues<QueryAllOAuthConnectionCommandResponseItem>("items", queryAllOAuthConnectionCommandResponse.items, serializeQueryAllOAuthConnectionCommandResponseItem);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeQueryAllOAuthConnectionCommandResponseItem(writer: SerializationWriter, queryAllOAuthConnectionCommandResponseItem: Partial<QueryAllOAuthConnectionCommandResponseItem> | undefined | null = {}) : void {
    if (queryAllOAuthConnectionCommandResponseItem) {
        serializeAuditsInfo(writer, queryAllOAuthConnectionCommandResponseItem)
        writer.writeStringValue("authorizeUrl", queryAllOAuthConnectionCommandResponseItem.authorizeUrl);
        writer.writeStringValue("iconUrl", queryAllOAuthConnectionCommandResponseItem.iconUrl);
        writer.writeGuidValue("id", queryAllOAuthConnectionCommandResponseItem.id);
        writer.writeStringValue("key", queryAllOAuthConnectionCommandResponseItem.key);
        writer.writeStringValue("name", queryAllOAuthConnectionCommandResponseItem.name);
        writer.writeStringValue("provider", queryAllOAuthConnectionCommandResponseItem.provider);
        writer.writeStringValue("wellKnown", queryAllOAuthConnectionCommandResponseItem.wellKnown);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeQueryAllOAuthPrividerCommandResponse(writer: SerializationWriter, queryAllOAuthPrividerCommandResponse: Partial<QueryAllOAuthPrividerCommandResponse> | undefined | null = {}) : void {
    if (queryAllOAuthPrividerCommandResponse) {
        writer.writeCollectionOfObjectValues<QueryAllOAuthPrividerCommandResponseItem>("items", queryAllOAuthPrividerCommandResponse.items, serializeQueryAllOAuthPrividerCommandResponseItem);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeQueryAllOAuthPrividerCommandResponseItem(writer: SerializationWriter, queryAllOAuthPrividerCommandResponseItem: Partial<QueryAllOAuthPrividerCommandResponseItem> | undefined | null = {}) : void {
    if (queryAllOAuthPrividerCommandResponseItem) {
        writer.writeStringValue("iconUrl", queryAllOAuthPrividerCommandResponseItem.iconUrl);
        writer.writeStringValue("name", queryAllOAuthPrividerCommandResponseItem.name);
        writer.writeGuidValue("oAuthId", queryAllOAuthPrividerCommandResponseItem.oAuthId);
        writer.writeStringValue("provider", queryAllOAuthPrividerCommandResponseItem.provider);
        writer.writeStringValue("redirectUrl", queryAllOAuthPrividerCommandResponseItem.redirectUrl);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeQueryServerInfoCommandResponse(writer: SerializationWriter, queryServerInfoCommandResponse: Partial<QueryServerInfoCommandResponse> | undefined | null = {}) : void {
    if (queryServerInfoCommandResponse) {
        writer.writeNumberValue("maxUploadFileSize", queryServerInfoCommandResponse.maxUploadFileSize);
        writer.writeStringValue("name", queryServerInfoCommandResponse.name);
        writer.writeStringValue("publicStoreUrl", queryServerInfoCommandResponse.publicStoreUrl);
        writer.writeStringValue("rsaPublic", queryServerInfoCommandResponse.rsaPublic);
        writer.writeStringValue("serviceUrl", queryServerInfoCommandResponse.serviceUrl);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeQuerySettingsCommandResponse(writer: SerializationWriter, querySettingsCommandResponse: Partial<QuerySettingsCommandResponse> | undefined | null = {}) : void {
    if (querySettingsCommandResponse) {
        writer.writeCollectionOfObjectValues<SettingItemResponse>("items", querySettingsCommandResponse.items, serializeSettingItemResponse);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeQueryUserBoundAccountsCommandResponse(writer: SerializationWriter, queryUserBoundAccountsCommandResponse: Partial<QueryUserBoundAccountsCommandResponse> | undefined | null = {}) : void {
    if (queryUserBoundAccountsCommandResponse) {
        writer.writeCollectionOfObjectValues<BoundAccountInfo>("items", queryUserBoundAccountsCommandResponse.items, serializeBoundAccountInfo);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRefreshTokenCommand(writer: SerializationWriter, refreshTokenCommand: Partial<RefreshTokenCommand> | undefined | null = {}) : void {
    if (refreshTokenCommand) {
        writer.writeStringValue("refreshToken", refreshTokenCommand.refreshToken);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRefreshTokenCommandResponse(writer: SerializationWriter, refreshTokenCommandResponse: Partial<RefreshTokenCommandResponse> | undefined | null = {}) : void {
    if (refreshTokenCommandResponse) {
        writer.writeStringValue("accessToken", refreshTokenCommandResponse.accessToken);
        writer.writeStringValue("expiresIn", refreshTokenCommandResponse.expiresIn);
        writer.writeStringValue("refreshToken", refreshTokenCommandResponse.refreshToken);
        writer.writeStringValue("tokenType", refreshTokenCommandResponse.tokenType);
        writer.writeStringValue("userId", refreshTokenCommandResponse.userId);
        writer.writeStringValue("userName", refreshTokenCommandResponse.userName);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRegisterUserCommand(writer: SerializationWriter, registerUserCommand: Partial<RegisterUserCommand> | undefined | null = {}) : void {
    if (registerUserCommand) {
        writer.writeStringValue("email", registerUserCommand.email);
        writer.writeStringValue("nickName", registerUserCommand.nickName);
        writer.writeStringValue("password", registerUserCommand.password);
        writer.writeStringValue("phone", registerUserCommand.phone);
        writer.writeStringValue("userName", registerUserCommand.userName);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeResetPasswordCommand(writer: SerializationWriter, resetPasswordCommand: Partial<ResetPasswordCommand> | undefined | null = {}) : void {
    if (resetPasswordCommand) {
        writer.writeStringValue("contextUserId", resetPasswordCommand.contextUserId);
        writer.writeEnumValue<UserType>("contextUserType", resetPasswordCommand.contextUserType);
        writer.writeStringValue("newPassword", resetPasswordCommand.newPassword);
        writer.writeStringValue("oldPassword", resetPasswordCommand.oldPassword);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSaveSettingCommand(writer: SerializationWriter, saveSettingCommand: Partial<SaveSettingCommand> | undefined | null = {}) : void {
    if (saveSettingCommand) {
        writer.writeStringValue("key", saveSettingCommand.key);
        writer.writeStringValue("value", saveSettingCommand.value);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSettingItemResponse(writer: SerializationWriter, settingItemResponse: Partial<SettingItemResponse> | undefined | null = {}) : void {
    if (settingItemResponse) {
        writer.writeStringValue("description", settingItemResponse.description);
        writer.writeStringValue("key", settingItemResponse.key);
        writer.writeStringValue("name", settingItemResponse.name);
        writer.writeStringValue("value", settingItemResponse.value);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSimpleGuid(writer: SerializationWriter, simpleGuid: Partial<SimpleGuid> | undefined | null = {}) : void {
    if (simpleGuid) {
        serializeSimpleOfGuid(writer, simpleGuid)
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSimpleLong(writer: SerializationWriter, simpleLong: Partial<SimpleLong> | undefined | null = {}) : void {
    if (simpleLong) {
        serializeSimpleOfLong(writer, simpleLong)
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSimpleOfGuid(writer: SerializationWriter, simpleOfGuid: Partial<SimpleOfGuid> | undefined | null = {}) : void {
    if (simpleOfGuid) {
        writer.writeGuidValue("value", simpleOfGuid.value);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSimpleOfLong(writer: SerializationWriter, simpleOfLong: Partial<SimpleOfLong> | undefined | null = {}) : void {
    if (simpleOfLong) {
        writer.writeStringValue("value", simpleOfLong.value);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUnbindUserOAuthCommand(writer: SerializationWriter, unbindUserOAuthCommand: Partial<UnbindUserOAuthCommand> | undefined | null = {}) : void {
    if (unbindUserOAuthCommand) {
        writer.writeStringValue("contextUserId", unbindUserOAuthCommand.contextUserId);
        writer.writeEnumValue<UserType>("contextUserType", unbindUserOAuthCommand.contextUserType);
        writer.writeGuidValue("providerId", unbindUserOAuthCommand.providerId);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdateOAuthConnectionCommand(writer: SerializationWriter, updateOAuthConnectionCommand: Partial<UpdateOAuthConnectionCommand> | undefined | null = {}) : void {
    if (updateOAuthConnectionCommand) {
        writer.writeStringValue("iconUrl", updateOAuthConnectionCommand.iconUrl);
        writer.writeStringValue("key", updateOAuthConnectionCommand.key);
        writer.writeStringValue("name", updateOAuthConnectionCommand.name);
        writer.writeGuidValue("oAuthConnectionId", updateOAuthConnectionCommand.oAuthConnectionId);
        writer.writeEnumValue<OAuthPrivider>("provider", updateOAuthConnectionCommand.provider);
        writer.writeStringValue("secret", updateOAuthConnectionCommand.secret);
        writer.writeStringValue("wellKnown", updateOAuthConnectionCommand.wellKnown);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdateUserAvatarCommand(writer: SerializationWriter, updateUserAvatarCommand: Partial<UpdateUserAvatarCommand> | undefined | null = {}) : void {
    if (updateUserAvatarCommand) {
        writer.writeStringValue("contextUserId", updateUserAvatarCommand.contextUserId);
        writer.writeEnumValue<UserType>("contextUserType", updateUserAvatarCommand.contextUserType);
        writer.writeStringValue("objectKey", updateUserAvatarCommand.objectKey);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdateUserInfoCommand(writer: SerializationWriter, updateUserInfoCommand: Partial<UpdateUserInfoCommand> | undefined | null = {}) : void {
    if (updateUserInfoCommand) {
        writer.writeStringValue("contextUserId", updateUserInfoCommand.contextUserId);
        writer.writeEnumValue<UserType>("contextUserType", updateUserInfoCommand.contextUserType);
        writer.writeStringValue("nickName", updateUserInfoCommand.nickName);
        writer.writeStringValue("phone", updateUserInfoCommand.phone);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUserStateInfo(writer: SerializationWriter, userStateInfo: Partial<UserStateInfo> | undefined | null = {}) : void {
    if (userStateInfo) {
        writer.writeStringValue("avatar", userStateInfo.avatar);
        writer.writeStringValue("email", userStateInfo.email);
        writer.writeBooleanValue("isAdmin", userStateInfo.isAdmin);
        writer.writeBooleanValue("isDeleted", userStateInfo.isDeleted);
        writer.writeBooleanValue("isDisable", userStateInfo.isDisable);
        writer.writeBooleanValue("isRoot", userStateInfo.isRoot);
        writer.writeStringValue("nickName", userStateInfo.nickName);
        writer.writeStringValue("phone", userStateInfo.phone);
        writer.writeStringValue("userId", userStateInfo.userId);
        writer.writeStringValue("userName", userStateInfo.userName);
    }
}
/**
 * 设置项.
 */
export interface SettingItemResponse extends Parsable {
    /**
     * 设置项描述.
     */
    description?: string | null;
    /**
     * 设置项 key.
     */
    key?: string | null;
    /**
     * 设置项名称.
     */
    name?: string | null;
    /**
     * 设置项当前值.
     */
    value?: string | null;
}
/**
 * SimpleGuid.
 */
export interface SimpleGuid extends Parsable, SimpleOfGuid {
}
/**
 * SimpleLong.
 */
export interface SimpleLong extends Parsable, SimpleOfLong {
}
/**
 * 简单类型.
 */
export interface SimpleOfGuid extends Parsable {
    /**
     * 任何类型.
     */
    value?: Guid | null;
}
/**
 * 简单类型.
 */
export interface SimpleOfLong extends Parsable {
    /**
     * 任何类型.
     */
    value?: string | null;
}
/**
 * 解绑第三方账号.
 */
export interface UnbindUserOAuthCommand extends Parsable {
    /**
     * 通过上下文自动配置id，前端不需要传递.
     */
    contextUserId?: string | null;
    /**
     * 通过上下文自动配置用户了偶像，前端不需要传递.
     */
    contextUserType?: UserType | null;
    /**
     * 第三方认证方式 id，对应 OauthConnection 表的 id.
     */
    providerId?: Guid | null;
}
/**
 * 更新第三方登录连接配置.
 */
export interface UpdateOAuthConnectionCommand extends Parsable {
    /**
     * 图标地址.
     */
    iconUrl?: string | null;
    /**
     * 应用 key.
     */
    key?: string | null;
    /**
     * 认证名称.
     */
    name?: string | null;
    /**
     * 连接 id.
     */
    oAuthConnectionId?: Guid | null;
    /**
     * 提供商.
     */
    provider?: OAuthPrivider | null;
    /**
     * 密钥，为空时保持不变.
     */
    secret?: string | null;
    /**
     * 发现端点.
     */
    wellKnown?: string | null;
}
/**
 * 更新用户头像.
 */
export interface UpdateUserAvatarCommand extends Parsable {
    /**
     * 通过上下文自动配置id，前端不需要传递.
     */
    contextUserId?: string | null;
    /**
     * 通过上下文自动配置用户了偶像，前端不需要传递.
     */
    contextUserType?: UserType | null;
    /**
     * 头像文件在存储中的 ObjectKey.
     */
    objectKey?: string | null;
}
/**
 * 更新用户基本信息.
 */
export interface UpdateUserInfoCommand extends Parsable {
    /**
     * 通过上下文自动配置id，前端不需要传递.
     */
    contextUserId?: string | null;
    /**
     * 通过上下文自动配置用户了偶像，前端不需要传递.
     */
    contextUserType?: UserType | null;
    /**
     * 昵称.
     */
    nickName?: string | null;
    /**
     * 手机号.
     */
    phone?: string | null;
}
/**
 * UserStateInfo.
 */
export interface UserStateInfo extends Parsable {
    /**
     * 头像地址.
     */
    avatar?: string | null;
    /**
     * 邮箱.
     */
    email?: string | null;
    /**
     * 是否管理员.
     */
    isAdmin?: boolean | null;
    /**
     * 已被删除.
     */
    isDeleted?: boolean | null;
    /**
     * 禁用.
     */
    isDisable?: boolean | null;
    /**
     * 是否超级管理员.
     */
    isRoot?: boolean | null;
    /**
     * 昵称.
     */
    nickName?: string | null;
    /**
     * 手机号.
     */
    phone?: string | null;
    /**
     * 用户ID.
     */
    userId?: string | null;
    /**
     * 用户名.
     */
    userName?: string | null;
}
export type UserType = (typeof UserTypeObject)[keyof typeof UserTypeObject];
/**
 * OAuth 提供商.
 */
export const OAuthPrividerObject = {
    Custom: "custom",
    Feishu: "feishu",
    DingTalk: "dingTalk",
} as const;
/**
 * 用户类型.
 */
export const UserTypeObject = {
    None: "none",
    External: "external",
    ExternalApp: "externalApp",
    Normal: "normal",
} as const;
/* tslint:enable */
/* eslint-enable */
