/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createCreateChatAppInstanceCommandResponseFromDiscriminatorValue, serializeCreateChatAppInstanceCommand, serializeCreateChatAppInstanceCommandResponse, type BusinessValidationResult, type CreateChatAppInstanceCommand, type CreateChatAppInstanceCommandResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/app/chatapp/create_chat
 */
export interface Create_chatRequestBuilder extends BaseRequestBuilder<Create_chatRequestBuilder> {
    /**
     * 创建对话.
     * @param body 创建对话应用实例.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CreateChatAppInstanceCommandResponse>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     post(body: CreateChatAppInstanceCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CreateChatAppInstanceCommandResponse | undefined>;
    /**
     * 创建对话.
     * @param body 创建对话应用实例.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateChatAppInstanceCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const Create_chatRequestBuilderUriTemplate = "{+baseurl}/api/app/chatapp/create_chat";
/**
 * Metadata for all the requests in the request builder.
 */
export const Create_chatRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: Create_chatRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCreateChatAppInstanceCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateChatAppInstanceCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
