/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createCreateAccessAppCommandResponseFromDiscriminatorValue, serializeCreateAccessAppCommand, serializeCreateAccessAppCommandResponse, type BusinessValidationResult, type CreateAccessAppCommand, type CreateAccessAppCommandResponse } from '../../models/index.js';
// @ts-ignore
import { AccessAppItemRequestBuilderRequestsMetadata, type AccessAppItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { ListRequestBuilderRequestsMetadata, type ListRequestBuilder } from './list/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/access-app
 */
export interface AccessAppRequestBuilder extends BaseRequestBuilder<AccessAppRequestBuilder> {
    /**
     * The list property
     */
    get list(): ListRequestBuilder;
    /**
     * Gets an item from the ApiSdk.api.accessApp.item collection
     * @param id 接入 id.
     * @returns {AccessAppItemRequestBuilder}
     */
     byId(id: Guid) : AccessAppItemRequestBuilder;
    /**
     * 创建应用接入，key 原文仅在创建响应返回一次；需要团队 Admin 及以上角色.
     * @param body 创建应用接入（团队下的 key，授权可访问哪些外部应用），需要团队 Admin 及以上角色.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CreateAccessAppCommandResponse>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     post(body: CreateAccessAppCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CreateAccessAppCommandResponse | undefined>;
    /**
     * 创建应用接入，key 原文仅在创建响应返回一次；需要团队 Admin 及以上角色.
     * @param body 创建应用接入（团队下的 key，授权可访问哪些外部应用），需要团队 Admin 及以上角色.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateAccessAppCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const AccessAppRequestBuilderUriTemplate = "{+baseurl}/api/access-app";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AccessAppRequestBuilderNavigationMetadata: Record<Exclude<keyof AccessAppRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: AccessAppItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
    list: {
        requestsMetadata: ListRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const AccessAppRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: AccessAppRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCreateAccessAppCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateAccessAppCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
