/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { GenerateRequestBuilderRequestsMetadata, type GenerateRequestBuilder } from './generate/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/wiki/{-id}/documents/{documentId}/chunks/metadata
 */
export interface MetadataRequestBuilder extends BaseRequestBuilder<MetadataRequestBuilder> {
    /**
     * The generate property
     */
    get generate(): GenerateRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const MetadataRequestBuilderUriTemplate = "{+baseurl}/api/wiki/{%2Did}/documents/{documentId}/chunks/metadata";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const MetadataRequestBuilderNavigationMetadata: Record<Exclude<keyof MetadataRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    generate: {
        requestsMetadata: GenerateRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
