/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createImportKnowledgeGraphFromFileResponseFromDiscriminatorValue, serializeImportKnowledgeGraphFromFileCommand, serializeImportKnowledgeGraphFromFileResponse, type BusinessValidationResult, type ImportKnowledgeGraphFromFileCommand, type ImportKnowledgeGraphFromFileResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/knowledge-graph/{id}/import-file
 */
export interface ImportFileRequestBuilder extends BaseRequestBuilder<ImportFileRequestBuilder> {
    /**
     * AI 导入文件生成图谱：提取文件内容后由对话模型按图谱现有模型抽取实体与关系写入图库（仅托管图 Admin+）.
     * @param body AI 导入文件生成图谱：读取已直传的文档文件，Maomi.ToMarkdown 提取内容后由对话模型按图谱现有模型抽取实体与关系写入图库，仅 Owner/Admin 的托管图可导入.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ImportKnowledgeGraphFromFileResponse>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     post(body: ImportKnowledgeGraphFromFileCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ImportKnowledgeGraphFromFileResponse | undefined>;
    /**
     * AI 导入文件生成图谱：提取文件内容后由对话模型按图谱现有模型抽取实体与关系写入图库（仅托管图 Admin+）.
     * @param body AI 导入文件生成图谱：读取已直传的文档文件，Maomi.ToMarkdown 提取内容后由对话模型按图谱现有模型抽取实体与关系写入图库，仅 Owner/Admin 的托管图可导入.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ImportKnowledgeGraphFromFileCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ImportFileRequestBuilderUriTemplate = "{+baseurl}/api/knowledge-graph/{id}/import-file";
/**
 * Metadata for all the requests in the request builder.
 */
export const ImportFileRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ImportFileRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createImportKnowledgeGraphFromFileResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeImportKnowledgeGraphFromFileCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
