/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { Clear_documentRequestBuilderRequestsMetadata, type Clear_documentRequestBuilder } from './clear_document/index.js';
// @ts-ignore
import { Complete_upload_documentRequestBuilderRequestsMetadata, type Complete_upload_documentRequestBuilder } from './complete_upload_document/index.js';
// @ts-ignore
import { Create_documentRequestBuilderRequestsMetadata, type Create_documentRequestBuilder } from './create_document/index.js';
// @ts-ignore
import { Delete_documentRequestBuilderRequestsMetadata, type Delete_documentRequestBuilder } from './delete_document/index.js';
// @ts-ignore
import { Document_infoRequestBuilderRequestsMetadata, type Document_infoRequestBuilder } from './document_info/index.js';
// @ts-ignore
import { Download_documentRequestBuilderRequestsMetadata, type Download_documentRequestBuilder } from './download_document/index.js';
// @ts-ignore
import { Embedding_documentRequestBuilderRequestsMetadata, type Embedding_documentRequestBuilder } from './embedding_document/index.js';
// @ts-ignore
import { Get_partition_documentRequestBuilderRequestsMetadata, type Get_partition_documentRequestBuilder } from './get_partition_document/index.js';
// @ts-ignore
import { ListRequestBuilderRequestsMetadata, type ListRequestBuilder } from './list/index.js';
// @ts-ignore
import { Preupload_documentRequestBuilderRequestsMetadata, type Preupload_documentRequestBuilder } from './preupload_document/index.js';
// @ts-ignore
import { SearchRequestBuilderRequestsMetadata, type SearchRequestBuilder } from './search/index.js';
// @ts-ignore
import { Task_listRequestBuilderRequestsMetadata, type Task_listRequestBuilder } from './task_list/index.js';
// @ts-ignore
import { Text_partition_documentRequestBuilderRequestsMetadata, type Text_partition_documentRequestBuilder } from './text_partition_document/index.js';
// @ts-ignore
import { type Update_document_file_nameRequestBuilder, Update_document_file_nameRequestBuilderRequestsMetadata } from './update_document_file_name/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/wiki/document
 */
export interface DocumentRequestBuilder extends BaseRequestBuilder<DocumentRequestBuilder> {
    /**
     * The clear_document property
     */
    get clear_document(): Clear_documentRequestBuilder;
    /**
     * The complete_upload_document property
     */
    get complete_upload_document(): Complete_upload_documentRequestBuilder;
    /**
     * The create_document property
     */
    get create_document(): Create_documentRequestBuilder;
    /**
     * The delete_document property
     */
    get delete_document(): Delete_documentRequestBuilder;
    /**
     * The document_info property
     */
    get document_info(): Document_infoRequestBuilder;
    /**
     * The download_document property
     */
    get download_document(): Download_documentRequestBuilder;
    /**
     * The embedding_document property
     */
    get embedding_document(): Embedding_documentRequestBuilder;
    /**
     * The get_partition_document property
     */
    get get_partition_document(): Get_partition_documentRequestBuilder;
    /**
     * The list property
     */
    get list(): ListRequestBuilder;
    /**
     * The preupload_document property
     */
    get preupload_document(): Preupload_documentRequestBuilder;
    /**
     * The search property
     */
    get search(): SearchRequestBuilder;
    /**
     * The task_list property
     */
    get task_list(): Task_listRequestBuilder;
    /**
     * The text_partition_document property
     */
    get text_partition_document(): Text_partition_documentRequestBuilder;
    /**
     * The update_document_file_name property
     */
    get update_document_file_name(): Update_document_file_nameRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const DocumentRequestBuilderUriTemplate = "{+baseurl}/api/wiki/document";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const DocumentRequestBuilderNavigationMetadata: Record<Exclude<keyof DocumentRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    clear_document: {
        requestsMetadata: Clear_documentRequestBuilderRequestsMetadata,
    },
    complete_upload_document: {
        requestsMetadata: Complete_upload_documentRequestBuilderRequestsMetadata,
    },
    create_document: {
        requestsMetadata: Create_documentRequestBuilderRequestsMetadata,
    },
    delete_document: {
        requestsMetadata: Delete_documentRequestBuilderRequestsMetadata,
    },
    document_info: {
        requestsMetadata: Document_infoRequestBuilderRequestsMetadata,
    },
    download_document: {
        requestsMetadata: Download_documentRequestBuilderRequestsMetadata,
    },
    embedding_document: {
        requestsMetadata: Embedding_documentRequestBuilderRequestsMetadata,
    },
    get_partition_document: {
        requestsMetadata: Get_partition_documentRequestBuilderRequestsMetadata,
    },
    list: {
        requestsMetadata: ListRequestBuilderRequestsMetadata,
    },
    preupload_document: {
        requestsMetadata: Preupload_documentRequestBuilderRequestsMetadata,
    },
    search: {
        requestsMetadata: SearchRequestBuilderRequestsMetadata,
    },
    task_list: {
        requestsMetadata: Task_listRequestBuilderRequestsMetadata,
    },
    text_partition_document: {
        requestsMetadata: Text_partition_documentRequestBuilderRequestsMetadata,
    },
    update_document_file_name: {
        requestsMetadata: Update_document_file_nameRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
