/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type UpdateRequestBuilder, UpdateRequestBuilderRequestsMetadata } from './update/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/aimodel/authorization/model
 */
export interface ModelRequestBuilder extends BaseRequestBuilder<ModelRequestBuilder> {
    /**
     * The update property
     */
    get update(): UpdateRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ModelRequestBuilderUriTemplate = "{+baseurl}/api/aimodel/authorization/model";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ModelRequestBuilderNavigationMetadata: Record<Exclude<keyof ModelRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    update: {
        requestsMetadata: UpdateRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
