<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<RootNamespace>MoAI.AIChannel</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\infra\MoAI.Infra.Shared\MoAI.Infra.Shared.csproj" />
		<ProjectReference Include="..\..\database\MoAI.Database.Shared\MoAI.Database.Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Agents.AI.OpenAI" />
		<PackageReference Include="Google.GenAI" />
		<PackageReference Include="Mscc.GenerativeAI.Microsoft" />
		<PackageReference Include="OllamaSharp" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Commands\" />
		<Folder Include="Queries\" />
		<Folder Include="Models\" />
	</ItemGroup>

</Project>
