/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AccountRequestBuilderNavigationMetadata, type AccountRequestBuilder } from './account/index.js';
// @ts-ignore
import { Admin_aimodelRequestBuilderNavigationMetadata, type Admin_aimodelRequestBuilder } from './admin_aimodel/index.js';
// @ts-ignore
import { Admin_pluginRequestBuilderNavigationMetadata, type Admin_pluginRequestBuilder } from './admin_plugin/index.js';
// @ts-ignore
import { Admin_promptRequestBuilderNavigationMetadata, type Admin_promptRequestBuilder } from './admin_prompt/index.js';
// @ts-ignore
import { AdminRequestBuilderNavigationMetadata, type AdminRequestBuilder } from './admin/index.js';
// @ts-ignore
import { AimodelRequestBuilderNavigationMetadata, type AimodelRequestBuilder } from './aimodel/index.js';
// @ts-ignore
import { AppRequestBuilderNavigationMetadata, type AppRequestBuilder } from './app/index.js';
// @ts-ignore
import { CommonRequestBuilderNavigationMetadata, type CommonRequestBuilder } from './common/index.js';
// @ts-ignore
import { DownloadRequestBuilderNavigationMetadata, type DownloadRequestBuilder } from './download/index.js';
// @ts-ignore
import { PromptRequestBuilderNavigationMetadata, type PromptRequestBuilder } from './prompt/index.js';
// @ts-ignore
import { StorageRequestBuilderNavigationMetadata, type StorageRequestBuilder } from './storage/index.js';
// @ts-ignore
import { type UserRequestBuilder, UserRequestBuilderNavigationMetadata } from './user/index.js';
// @ts-ignore
import { type WikiRequestBuilder, WikiRequestBuilderNavigationMetadata } from './wiki/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api
 */
export interface ApiRequestBuilder extends BaseRequestBuilder<ApiRequestBuilder> {
    /**
     * The account property
     */
    get account(): AccountRequestBuilder;
    /**
     * The admin property
     */
    get admin(): AdminRequestBuilder;
    /**
     * The admin_aimodel property
     */
    get admin_aimodel(): Admin_aimodelRequestBuilder;
    /**
     * The admin_plugin property
     */
    get admin_plugin(): Admin_pluginRequestBuilder;
    /**
     * The admin_prompt property
     */
    get admin_prompt(): Admin_promptRequestBuilder;
    /**
     * The aimodel property
     */
    get aimodel(): AimodelRequestBuilder;
    /**
     * The app property
     */
    get app(): AppRequestBuilder;
    /**
     * The common property
     */
    get common(): CommonRequestBuilder;
    /**
     * The download property
     */
    get download(): DownloadRequestBuilder;
    /**
     * The prompt property
     */
    get prompt(): PromptRequestBuilder;
    /**
     * The storage property
     */
    get storage(): StorageRequestBuilder;
    /**
     * The user property
     */
    get user(): UserRequestBuilder;
    /**
     * The wiki property
     */
    get wiki(): WikiRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ApiRequestBuilderUriTemplate = "{+baseurl}/api";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ApiRequestBuilderNavigationMetadata: Record<Exclude<keyof ApiRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    account: {
        navigationMetadata: AccountRequestBuilderNavigationMetadata,
    },
    admin: {
        navigationMetadata: AdminRequestBuilderNavigationMetadata,
    },
    admin_aimodel: {
        navigationMetadata: Admin_aimodelRequestBuilderNavigationMetadata,
    },
    admin_plugin: {
        navigationMetadata: Admin_pluginRequestBuilderNavigationMetadata,
    },
    admin_prompt: {
        navigationMetadata: Admin_promptRequestBuilderNavigationMetadata,
    },
    aimodel: {
        navigationMetadata: AimodelRequestBuilderNavigationMetadata,
    },
    app: {
        navigationMetadata: AppRequestBuilderNavigationMetadata,
    },
    common: {
        navigationMetadata: CommonRequestBuilderNavigationMetadata,
    },
    download: {
        navigationMetadata: DownloadRequestBuilderNavigationMetadata,
    },
    prompt: {
        navigationMetadata: PromptRequestBuilderNavigationMetadata,
    },
    storage: {
        navigationMetadata: StorageRequestBuilderNavigationMetadata,
    },
    user: {
        navigationMetadata: UserRequestBuilderNavigationMetadata,
    },
    wiki: {
        navigationMetadata: WikiRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
