/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { PluginRequestBuilderNavigationMetadata, PluginRequestBuilderRequestsMetadata, type PluginRequestBuilder } from './plugin/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/ai
 */
export interface AiRequestBuilder extends BaseRequestBuilder<AiRequestBuilder> {
    /**
     * The plugin property
     */
    get plugin(): PluginRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AiRequestBuilderUriTemplate = "{+baseurl}/api/ai";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AiRequestBuilderNavigationMetadata: Record<Exclude<keyof AiRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    plugin: {
        requestsMetadata: PluginRequestBuilderRequestsMetadata,
        navigationMetadata: PluginRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
