ALTER TABLE `oauth_connection`
ADD COLUMN `create_user_id` int DEFAULT 0 NOT NULL COMMENT '创建人',
ADD COLUMN `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间',
ADD COLUMN `update_user_id` int DEFAULT 0 NOT NULL COMMENT '更新人',
ADD COLUMN `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL COMMENT '更新时间',
ADD COLUMN `is_deleted` bigint DEFAULT 0 NOT NULL COMMENT '软删除';
