-- 飞书通知模块（连接复用 + 渠道绑定）schema 变更
-- 用法（存量库）：
--   docker exec -i moai-postgres psql -U postgres -d moai < asserts/feishu_app.sql
-- 新库由 EnsureCreated 依据实体/配置直接建成，无需执行本脚本。
-- 执行后请重跑 tool/PostgresScaffold 逆向生成，保持库与实体一致。

-- 飞书应用：一个飞书开放平台应用（AppID/AppSecret）对应一条长连接，事件由飞书模块统一接收后按绑定转发
create table if not exists feishu_app (
  id uuid not null default uuid_generate_v4(),
  name varchar(50) not null,
  description varchar(255) not null default ''::character varying,
  team_id integer not null,
  app_id varchar(64) not null,
  app_secret varchar(128) not null,
  domain varchar(100) not null default 'https://open.feishu.cn'::character varying,
  is_disable boolean not null default false,
  create_user_id bigint not null default 0,
  create_time timestamptz not null default timezone('utc',now()),
  update_user_id bigint not null default 0,
  update_time timestamptz not null default timezone('utc',now()),
  is_deleted bigint not null default 0,
  constraint feishu_app_pkey primary key (id)
);
comment on table feishu_app is '飞书应用，一个飞书开放平台应用对应一条长连接，事件统一接收后按绑定转发';
comment on column feishu_app.id is 'id';
comment on column feishu_app.name is '连接名称，团队内唯一';
comment on column feishu_app.description is '描述';
comment on column feishu_app.team_id is '团队id';
comment on column feishu_app.app_id is '飞书开放平台 AppID，形如 cli_xxx，全局唯一';
comment on column feishu_app.app_secret is '飞书开放平台 AppSecret';
comment on column feishu_app.domain is '接入域名，飞书为 https://open.feishu.cn，Lark 为 https://open.larksuite.com';
comment on column feishu_app.is_disable is '禁用，禁用后断开长连接且不再接收事件';
comment on column feishu_app.create_time is '创建时间';
comment on column feishu_app.create_user_id is '创建人';
comment on column feishu_app.update_time is '更新时间';
comment on column feishu_app.update_user_id is '更新人';
comment on column feishu_app.is_deleted is '软删除';

create unique index if not exists idx_feishu_app_app_id_uindex on feishu_app (app_id) where (is_deleted = 0);
create index if not exists idx_feishu_app_team_id_index on feishu_app (team_id);

-- 飞书应用绑定：将飞书应用绑定到应用等渠道；同一飞书应用同时只能绑定一个渠道
create table if not exists feishu_app_binding (
  id bigint generated by default as identity,
  feishu_app_id uuid not null,
  channel_type integer not null,
  channel_id varchar(64) not null,
  create_user_id bigint not null default 0,
  create_time timestamptz not null default timezone('utc',now()),
  update_user_id bigint not null default 0,
  update_time timestamptz not null default timezone('utc',now()),
  is_deleted bigint not null default 0,
  constraint feishu_app_binding_pkey primary key (id)
);
comment on table feishu_app_binding is '飞书应用绑定，将飞书应用绑定到应用等渠道；同一飞书应用同时只能绑定一个渠道';
comment on column feishu_app_binding.id is '自增主键';
comment on column feishu_app_binding.feishu_app_id is '飞书应用记录 id（feishu_app.id，逻辑关联，仓库约定不建物理外键）';
comment on column feishu_app_binding.channel_type is '渠道类型，见 FeishuChannelType（当前仅 app）';
comment on column feishu_app_binding.channel_id is '渠道记录 id 字符串，应用渠道为 app.id（uuid）';
comment on column feishu_app_binding.create_time is '创建时间';
comment on column feishu_app_binding.create_user_id is '创建人';
comment on column feishu_app_binding.update_time is '更新时间';
comment on column feishu_app_binding.update_user_id is '更新人';
comment on column feishu_app_binding.is_deleted is '软删除';

-- 核心约束：同一飞书应用（未删除）只能有一条绑定，避免多渠道重复消费同一事件
create unique index if not exists idx_feishu_app_binding_feishu_app_uindex on feishu_app_binding (feishu_app_id) where (is_deleted = 0);
create index if not exists idx_feishu_app_binding_channel_index on feishu_app_binding (channel_type, channel_id);
