-- 团队插件模块增量 DDL：plugin_team_authorization（私有系统插件→团队授权）
-- 本仓库无 EF Migration（启动 EnsureCreated 只对空库生效），
-- 已有数据库新增表需手动执行本文件；同时保持与
-- src/database 下 PluginTeamAuthorizationEntity 及其 Configuration 一致。
-- 软删除为 bigint ticks（同既有插件表约定，审计钩子自动写入）。
--
-- 语义：系统插件记录（plugin）可为公开（is_public=true，所有团队可用）或私有（is_public=false）。
-- 私有系统插件需在本表按 plugin_id + team_id 授权团队，被授权团队即可使用。

CREATE TABLE IF NOT EXISTS public.plugin_team_authorization (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plugin_id       uuid         NOT NULL,
    team_id         int          NOT NULL,
    is_deleted      bigint       NOT NULL DEFAULT 0,
    create_user_id  bigint       NOT NULL DEFAULT 0,
    create_time     timestamptz  NOT NULL DEFAULT timezone('utc'::text, now()),
    update_user_id  bigint       NOT NULL DEFAULT 0,
    update_time     timestamptz  NOT NULL DEFAULT timezone('utc'::text, now())
);

COMMENT ON TABLE public.plugin_team_authorization IS '授权私有系统插件给哪些团队使用';
COMMENT ON COLUMN public.plugin_team_authorization.id IS '自增主键';
COMMENT ON COLUMN public.plugin_team_authorization.plugin_id IS '系统插件记录 id（plugin.id，逻辑关联，仓库约定不建物理外键）';
COMMENT ON COLUMN public.plugin_team_authorization.team_id IS '授权团队id，该团队成员可以使用该私有插件（逻辑关联 team.id）';
COMMENT ON COLUMN public.plugin_team_authorization.is_deleted IS '软删除：0=未删除，非0=已删除（审计钩子自动写入）';
COMMENT ON COLUMN public.plugin_team_authorization.create_user_id IS '创建人用户ID，审计钩子插入时自动填充';
COMMENT ON COLUMN public.plugin_team_authorization.create_time IS '创建时间，审计钩子自动填充，默认timezone(utc,now())';
COMMENT ON COLUMN public.plugin_team_authorization.update_user_id IS '最后修改人用户ID，审计钩子更新/删除时自动填充';
COMMENT ON COLUMN public.plugin_team_authorization.update_time IS '更新时间，审计钩子插入/更新/删除时自动刷新';

CREATE INDEX IF NOT EXISTS idx_plugin_team_authorization_plugin_id ON public.plugin_team_authorization (plugin_id);
CREATE INDEX IF NOT EXISTS idx_plugin_team_authorization_team_id ON public.plugin_team_authorization (team_id);
-- partial 唯一索引：同一插件对同一团队仅一条未删除授权，取消授权后可重新授权
CREATE UNIQUE INDEX IF NOT EXISTS idx_plugin_team_authorization_plugin_team_uindex
    ON public.plugin_team_authorization (plugin_id, team_id) WHERE is_deleted = 0;

ALTER TABLE public.plugin_team_authorization
    OWNER to postgres;
