-- 提示词模块（prompt）schema 变更
-- 用法（存量库）：
--   docker exec -i moai-postgres psql -U postgres -d moai < asserts/prompt.sql
-- 新库由 EnsureCreated 依据实体/配置直接建成，无需执行本脚本。

-- 提示词：个人提示词（team_id=0，仅创建人可见可用）、团队提示词（team_id>0，团队 Admin 创建、成员可用），
-- 申请上架（publication_review，resource_type=prompt）审批通过后 is_public 置为 true，进入提示词市场
create table if not exists prompt (
  id integer generated by default as identity,
  name varchar(20) not null,
  description varchar(255) not null default ''::character varying,
  content text not null,
  prompt_class_id integer not null,
  avatar_path varchar(255) not null default ''::character varying,
  is_public boolean not null default false,
  is_audit boolean not null default false,
  counter integer not null default 0,
  create_user_id bigint not null default 0,
  create_time timestamptz not null default timezone('utc',now()),
  update_user_id bigint not null default 0,
  update_time timestamptz not null default timezone('utc',now()),
  is_deleted bigint not null default 0,
  team_id integer not null default 0,
  constraint idx_prompt_primary primary key (id)
);
comment on table prompt is '提示词';
comment on column prompt.id is 'id';
comment on column prompt.name is '名称';
comment on column prompt.description is '描述';
comment on column prompt.content is '提示词内容';
comment on column prompt.prompt_class_id is '分类id';
comment on column prompt.avatar_path is '头像地址';
comment on column prompt.is_public is '是否公开';
comment on column prompt.is_audit is '审核通过';
comment on column prompt.counter is '计数器，市场提示词被他人查看一次加一';
-- 存量库补充列：专家使用次数（绑定为会话/用户默认专家时加一）
alter table prompt add column if not exists use_count integer not null default 0;
comment on column prompt.use_count is '被选为专家提示词的使用次数，每次绑定时加一';
comment on column prompt.create_user_id is '创建人';
comment on column prompt.create_time is '创建时间';
comment on column prompt.update_user_id is '更新人';
comment on column prompt.update_time is '更新时间';
comment on column prompt.is_deleted is '软删除';
comment on column prompt.team_id is '所属团队id，0 表示个人提示词';
