-- 上架审核模块（publication_review）schema 变更
-- 用法（存量库）：
--   docker exec -i moai-postgres psql -U postgres -d moai < asserts/publication_review.sql
-- 新库由 EnsureCreated 依据实体/配置直接建成，无需执行本脚本。

-- 上架审核：应用/提示词等资源公开到平台（is_public）前需系统管理员审批，
-- 审批通过后由系统将目标资源 is_public 置为 true
create table if not exists publication_review (
  id bigint generated by default as identity,
  resource_type integer not null,
  resource_id varchar(64) not null,
  resource_name varchar(100) not null default ''::character varying,
  team_id integer not null,
  apply_reason varchar(255) not null default ''::character varying,
  state integer not null default 0,
  review_comment varchar(255) not null default ''::character varying,
  review_time timestamptz null,
  create_user_id bigint not null default 0,
  create_time timestamptz not null default timezone('utc',now()),
  update_user_id bigint not null default 0,
  update_time timestamptz not null default timezone('utc',now()),
  is_deleted bigint not null default 0,
  constraint publication_review_pkey primary key (id)
);
comment on table publication_review is '上架审核，资源公开到平台前需系统管理员审批';
comment on column publication_review.id is '自增主键';
comment on column publication_review.resource_type is '资源类型，见 PublicationResourceType（应用=0，提示词=1）';
comment on column publication_review.resource_id is '资源 id 字符串，应用为 app.id（uuid），提示词为 prompt.id（数字）';
comment on column publication_review.resource_name is '资源名称快照，申请时的资源名称';
comment on column publication_review.team_id is '资源所属团队id';
comment on column publication_review.apply_reason is '申请说明';
comment on column publication_review.state is '审核状态，见 PublicationState（待审核=0，已通过=1，已驳回=2）';
comment on column publication_review.review_comment is '审批意见';
comment on column publication_review.review_time is '审批时间，未审批为 null';
comment on column publication_review.create_user_id is '创建人（申请人）';
comment on column publication_review.create_time is '创建时间';
comment on column publication_review.update_user_id is '更新人（审批人）';
comment on column publication_review.update_time is '更新时间';
comment on column publication_review.is_deleted is '软删除';

-- 核心约束：同一资源（未删除）同时只能有一条待审核申请
create unique index if not exists ux_publication_review_resource_pending on publication_review (resource_type, resource_id) where (is_deleted = 0 AND state = 0);
create index if not exists idx_publication_review_team_id on publication_review (team_id);
