-- 团队模块增量 DDL：team（团队）/ team_user（团队成员）
-- 本仓库无 EF Migration（启动 EnsureCreated 只对空库生效），
-- 已有数据库新增表需手动执行本文件；同时保持与
-- src/database 下 TeamEntity/TeamUserEntity 及其 Configuration 一致。
-- 列注释与实体 XML 注释同义，冲突时以实体注释为准。
--
-- 软删除说明：本模块 is_deleted 为 boolean（区别于既有表的 bigint ticks，审计钩子经接口适配自动写入），
-- 唯一约束采用 partial index（仅约束未删除行），因此"删除后同名重建 / 移除后重新加入"可无限次进行。

CREATE TABLE IF NOT EXISTS public.team (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(50)  NOT NULL,
    description     varchar(255) NOT NULL DEFAULT '',
    avatar_path     varchar(255) NOT NULL DEFAULT '',
    is_disable      boolean      NOT NULL DEFAULT false,
    is_deleted      boolean      NOT NULL DEFAULT false,
    create_user_id  bigint       NOT NULL DEFAULT 0,
    create_time     timestamptz  NOT NULL DEFAULT timezone('utc'::text, now()),
    update_user_id  bigint       NOT NULL DEFAULT 0,
    update_time     timestamptz  NOT NULL DEFAULT timezone('utc'::text, now())
);

COMMENT ON TABLE public.team IS '团队，知识库/插件等资源的管理单元';
COMMENT ON COLUMN public.team.id IS '团队ID，自增主键';
COMMENT ON COLUMN public.team.name IS '团队名称，最长50字符';
COMMENT ON COLUMN public.team.description IS '团队简介，最长255字符，空串=未填写';
COMMENT ON COLUMN public.team.avatar_path IS '团队头像的存储ObjectKey（桶内路径），非完整URL，展示时经GetPublicFileUrl转公开地址，空串=未设置';
COMMENT ON COLUMN public.team.is_disable IS '是否禁用团队：true=团队及下级资源停用，由管理员操作，不影响成员账号登录';
COMMENT ON COLUMN public.team.is_deleted IS '软删除：false=未删除，true=已删除（审计钩子经接口适配自动写入）';
COMMENT ON COLUMN public.team.create_user_id IS '创建人用户ID，审计钩子插入时自动填充';
COMMENT ON COLUMN public.team.create_time IS '创建时间，审计钩子自动填充，默认timezone(utc,now())';
COMMENT ON COLUMN public.team.update_user_id IS '最后修改人用户ID，审计钩子更新/删除时自动填充';
COMMENT ON COLUMN public.team.update_time IS '更新时间，审计钩子插入/更新/删除时自动刷新';

-- partial 唯一索引：仅约束未删除行，删除后同名可重建，删除历史不限数量
CREATE UNIQUE INDEX IF NOT EXISTS idx_team_name_live_uindex ON public.team (name) WHERE is_deleted = false;

ALTER TABLE public.team
    OWNER to postgres;


CREATE TABLE IF NOT EXISTS public.team_user (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id         bigint       NOT NULL,
    user_id         bigint       NOT NULL,
    role            int          NOT NULL DEFAULT 2,
    is_deleted      boolean      NOT NULL DEFAULT false,
    create_user_id  bigint       NOT NULL DEFAULT 0,
    create_time     timestamptz  NOT NULL DEFAULT timezone('utc'::text, now()),
    update_user_id  bigint       NOT NULL DEFAULT 0,
    update_time     timestamptz  NOT NULL DEFAULT timezone('utc'::text, now())
);

COMMENT ON TABLE public.team_user IS '团队成员，用户与团队多对多关联';
COMMENT ON COLUMN public.team_user.id IS '自增主键';
COMMENT ON COLUMN public.team_user.team_id IS '所属团队ID，逻辑关联team.id（仓库约定不建物理外键）';
COMMENT ON COLUMN public.team_user.user_id IS '成员用户ID，逻辑关联user.id（仓库约定不建物理外键）';
COMMENT ON COLUMN public.team_user.role IS '成员角色：0=Owner(所有者，可解散/转让/管理一切) 1=Admin(可管理成员、创建团队资源) 2=Member(普通成员)，新成员默认2';
COMMENT ON COLUMN public.team_user.is_deleted IS '软删除：false=在团队中，true=已移出（审计钩子经接口适配自动写入）';
COMMENT ON COLUMN public.team_user.create_user_id IS '邀请人用户ID，审计钩子插入时自动填充';
COMMENT ON COLUMN public.team_user.create_time IS '加入时间，审计钩子自动填充，默认timezone(utc,now())';
COMMENT ON COLUMN public.team_user.update_user_id IS '最后修改人用户ID，角色变更/移除时审计钩子自动填充';
COMMENT ON COLUMN public.team_user.update_time IS '更新时间，审计钩子插入/更新/删除时自动刷新';

CREATE INDEX IF NOT EXISTS idx_team_user_team_id ON public.team_user (team_id);
CREATE INDEX IF NOT EXISTS idx_team_user_user_id ON public.team_user (user_id);
-- partial 唯一索引：仅约束在团成员，移除后可重新加入，移除历史不限数量
CREATE UNIQUE INDEX IF NOT EXISTS idx_team_user_team_user_live_uindex ON public.team_user (team_id, user_id) WHERE is_deleted = false;

ALTER TABLE public.team_user
    OWNER to postgres;
