-- 知识库外部源（wiki_source / wiki_source_document）schema 变更
-- 用法（存量库）：
--   docker exec -i moai-postgres psql -U postgres -d moai < asserts/wiki_source.sql
-- 新库由 EnsureCreated 依据实体/配置直接建成，无需执行本脚本。
-- 执行后请重跑 tool/PostgresScaffold 逆向生成，保持库与实体一致。

-- 外部源：知识库下的一类外部数据入口（飞书文档 / 爬虫），持有同步方式与工作流预设
create table if not exists wiki_source (
  id uuid not null default uuid_generate_v4(),
  wiki_id integer not null,
  team_id integer not null,
  source_type integer not null default 0,
  name varchar(50) not null,
  description varchar(255) not null default ''::character varying,
  config text not null default ''::text,
  workflow_config text not null default ''::text,
  is_enable boolean not null default true,
  cron varchar(64) not null default ''::character varying,
  is_event_subscription boolean not null default false,
  last_sync_time timestamptz,
  last_sync_status integer not null default 0,
  last_sync_message varchar(1000) not null default ''::character varying,
  create_user_id bigint not null default 0,
  create_time timestamptz not null default timezone('utc', now()),
  update_user_id bigint not null default 0,
  update_time timestamptz not null default timezone('utc', now()),
  is_deleted bigint not null default 0,
  constraint wiki_source_pkey primary key (id)
);
comment on table wiki_source is '知识库外部源，飞书文档/爬虫等外部数据入口，持有同步方式与工作流预设';
comment on column wiki_source.id is 'id';
comment on column wiki_source.wiki_id is '知识库id';
comment on column wiki_source.team_id is '团队id，冗余便于权限校验与查询';
comment on column wiki_source.source_type is '外部源类型，见 WikiSourceType（0=飞书文档，1=爬虫）';
comment on column wiki_source.name is '外部源名称，知识库内唯一';
comment on column wiki_source.description is '描述';
comment on column wiki_source.config is '外部源连接配置 JSON（飞书文档源：飞书应用连接id、节点token、空间id、是否含子文档等）';
comment on column wiki_source.workflow_config is '外部源工作流配置 JSON（切割/元数据/向量化三步预设），空串表示回退知识库默认工作流';
comment on column wiki_source.is_enable is '启用，停用后不再手动/定时/事件同步';
comment on column wiki_source.cron is '定时同步 cron 表达式（UTC），空串表示未开启定时同步';
comment on column wiki_source.is_event_subscription is '是否开启飞书事件订阅，开启后文档变更事件到达即触发重新拉取';
comment on column wiki_source.last_sync_time is '最近一次同步时间';
comment on column wiki_source.last_sync_status is '最近一次同步状态，见 WikiSourceSyncStatus（0=未同步，1=成功，2=失败）';
comment on column wiki_source.last_sync_message is '最近一次同步结果摘要或错误信息';
comment on column wiki_source.create_time is '创建时间';
comment on column wiki_source.create_user_id is '创建人';
comment on column wiki_source.update_time is '更新时间';
comment on column wiki_source.update_user_id is '更新人';
comment on column wiki_source.is_deleted is '软删除';

create unique index if not exists idx_wiki_source_wiki_name_uindex on wiki_source (wiki_id, name) where (is_deleted = 0);
create index if not exists idx_wiki_source_wiki_id_index on wiki_source (wiki_id);
create index if not exists idx_wiki_source_team_id_index on wiki_source (team_id);

-- 外部源文档：外部源条目与知识库文档的映射，记录内容哈希用于增量比对
create table if not exists wiki_source_document (
  id bigint generated by default as identity,
  source_id uuid not null,
  wiki_id integer not null,
  team_id integer not null,
  document_id integer not null,
  external_key varchar(128) not null,
  external_doc_token varchar(128) not null default ''::character varying,
  external_title varchar(255) not null default ''::character varying,
  external_path varchar(1000) not null default ''::character varying,
  content_hash varchar(64) not null default ''::character varying,
  revision varchar(64) not null default ''::character varying,
  status integer not null default 0,
  last_sync_time timestamptz,
  last_error varchar(1000) not null default ''::character varying,
  create_user_id bigint not null default 0,
  create_time timestamptz not null default timezone('utc', now()),
  update_user_id bigint not null default 0,
  update_time timestamptz not null default timezone('utc', now()),
  is_deleted bigint not null default 0,
  constraint wiki_source_document_pkey primary key (id)
);
comment on table wiki_source_document is '外部源文档，外部源条目与知识库文档的映射，记录内容哈希用于增量比对';
comment on column wiki_source_document.id is '自增主键';
comment on column wiki_source_document.source_id is '外部源id（wiki_source.id，逻辑关联，仓库约定不建物理外键）';
comment on column wiki_source_document.wiki_id is '知识库id';
comment on column wiki_source_document.team_id is '团队id';
comment on column wiki_source_document.document_id is '知识库文档id（wiki_document.id，逻辑关联）';
comment on column wiki_source_document.external_key is '外部文档唯一标识，飞书文档源为节点token';
comment on column wiki_source_document.external_title is '外部文档标题';
comment on column wiki_source_document.external_path is '外部文档在源中的路径（面包屑，斜杠分隔）';
comment on column wiki_source_document.content_hash is '最近一次同步内容的 SHA-256，用于判断是否变化';
comment on column wiki_source_document.revision is '外部文档版本号（飞书为文档编辑时间/版本号），辅助判断变化';
comment on column wiki_source_document.status is '同步状态，见 WikiSourceDocumentStatus（0=待同步，1=已同步，2=失败）';
comment on column wiki_source_document.last_sync_time is '最近一次同步时间';
comment on column wiki_source_document.last_error is '最近一次同步错误信息';
comment on column wiki_source_document.create_time is '创建时间';
comment on column wiki_source_document.create_user_id is '创建人';
comment on column wiki_source_document.update_time is '更新时间';
comment on column wiki_source_document.update_user_id is '更新人';
comment on column wiki_source_document.is_deleted is '软删除';

-- 存量库补列（幂等）：云文档变更事件带的是文档 token，需与节点 token 分开存
alter table wiki_source_document add column if not exists external_doc_token varchar(128) not null default ''::character varying;
comment on column wiki_source_document.external_doc_token is '外部文档内容标识，飞书文档源为文档token（obj_token），云文档变更事件按此匹配';

create unique index if not exists idx_wiki_source_document_key_uindex on wiki_source_document (source_id, external_key) where (is_deleted = 0);
create index if not exists idx_wiki_source_document_source_id_index on wiki_source_document (source_id);
create index if not exists idx_wiki_source_document_doc_token_index on wiki_source_document (source_id, external_doc_token);
create index if not exists idx_wiki_source_document_wiki_id_index on wiki_source_document (wiki_id);
create index if not exists idx_wiki_source_document_document_id_index on wiki_source_document (document_id);
