/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createQueryInternalTemplatePluginListCommandResponseFromDiscriminatorValue, serializeQueryInternalTemplatePluginListCommand, serializeQueryInternalTemplatePluginListCommandResponse, type BusinessValidationResult, type QueryInternalTemplatePluginListCommand, type QueryInternalTemplatePluginListCommandResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/admin_plugin/internal_template_list
 */
export interface Internal_template_listRequestBuilder extends BaseRequestBuilder<Internal_template_listRequestBuilder> {
    /**
     * 获取内置插件模板列表.
     * @param body 查询内置插件模板列表.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<QueryInternalTemplatePluginListCommandResponse>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     post(body: QueryInternalTemplatePluginListCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<QueryInternalTemplatePluginListCommandResponse | undefined>;
    /**
     * 获取内置插件模板列表.
     * @param body 查询内置插件模板列表.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: QueryInternalTemplatePluginListCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const Internal_template_listRequestBuilderUriTemplate = "{+baseurl}/api/admin_plugin/internal_template_list";
/**
 * Metadata for all the requests in the request builder.
 */
export const Internal_template_listRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: Internal_template_listRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createQueryInternalTemplatePluginListCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeQueryInternalTemplatePluginListCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
