/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createQueryWorkflowDefinitionCommandResponseFromDiscriminatorValue, serializeQueryWorkflowDefinitionCommand, serializeQueryWorkflowDefinitionCommandResponse, type BusinessValidationResult, type QueryWorkflowDefinitionCommand, type QueryWorkflowDefinitionCommandResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/team/workflowapp/config
 */
export interface ConfigRequestBuilder extends BaseRequestBuilder<ConfigRequestBuilder> {
    /**
     * 获取工作流定义.检索单个工作流定义的完整信息，包括所有节点配置和连接.
     * @param body 查询工作流定义命令.用于检索单个工作流定义的完整信息，包括所有节点配置和连接.基础信息（Name、Description、Avatar）来自 AppEntity.设计数据（UiDesign、FunctionDesign）来自 AppWorkflowDesignEntity.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<QueryWorkflowDefinitionCommandResponse>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     post(body: QueryWorkflowDefinitionCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<QueryWorkflowDefinitionCommandResponse | undefined>;
    /**
     * 获取工作流定义.检索单个工作流定义的完整信息，包括所有节点配置和连接.
     * @param body 查询工作流定义命令.用于检索单个工作流定义的完整信息，包括所有节点配置和连接.基础信息（Name、Description、Avatar）来自 AppEntity.设计数据（UiDesign、FunctionDesign）来自 AppWorkflowDesignEntity.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: QueryWorkflowDefinitionCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ConfigRequestBuilderUriTemplate = "{+baseurl}/api/team/workflowapp/config";
/**
 * Metadata for all the requests in the request builder.
 */
export const ConfigRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ConfigRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createQueryWorkflowDefinitionCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeQueryWorkflowDefinitionCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
