/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type UserRequestBuilder, UserRequestBuilderNavigationMetadata } from './user/index.js';
// @ts-ignore
import { type UsersRequestBuilder, UsersRequestBuilderRequestsMetadata } from './users/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/usermanage
 */
export interface UsermanageRequestBuilder extends BaseRequestBuilder<UsermanageRequestBuilder> {
    /**
     * The user property
     */
    get user(): UserRequestBuilder;
    /**
     * The users property
     */
    get users(): UsersRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const UsermanageRequestBuilderUriTemplate = "{+baseurl}/api/usermanage";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const UsermanageRequestBuilderNavigationMetadata: Record<Exclude<keyof UsermanageRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    user: {
        navigationMetadata: UserRequestBuilderNavigationMetadata,
    },
    users: {
        requestsMetadata: UsersRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
