/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createRunTestNativePluginCommandResponseFromDiscriminatorValue, serializeRunTestNativePluginCommand, serializeRunTestNativePluginCommandResponse, type BusinessValidationResult, type RunTestNativePluginCommand, type RunTestNativePluginCommandResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/admin/native_plugin/run_test
 */
export interface Run_testRequestBuilder extends BaseRequestBuilder<Run_testRequestBuilder> {
    /**
     * 运行插件测试（调试）.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<RunTestNativePluginCommandResponse>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     post(body: RunTestNativePluginCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<RunTestNativePluginCommandResponse | undefined>;
    /**
     * 运行插件测试（调试）.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: RunTestNativePluginCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const Run_testRequestBuilderUriTemplate = "{+baseurl}/api/admin/native_plugin/run_test";
/**
 * Metadata for all the requests in the request builder.
 */
export const Run_testRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: Run_testRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createRunTestNativePluginCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeRunTestNativePluginCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
