/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createSimpleGuidFromDiscriminatorValue, serializeSaveTeamMcpPluginCommand, serializeSimpleGuid, type BusinessValidationResult, type SaveTeamMcpPluginCommand, type SimpleGuid } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/team/{-id}/plugin/mcp
 */
export interface McpRequestBuilder extends BaseRequestBuilder<McpRequestBuilder> {
    /**
     * 导入/更新团队 MCP 插件，需团队 Owner/Admin.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SimpleGuid>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     post(body: SaveTeamMcpPluginCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SimpleGuid | undefined>;
    /**
     * 导入/更新团队 MCP 插件，需团队 Owner/Admin.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: SaveTeamMcpPluginCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const McpRequestBuilderUriTemplate = "{+baseurl}/api/team/{%2Did}/plugin/mcp";
/**
 * Metadata for all the requests in the request builder.
 */
export const McpRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: McpRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSimpleGuidFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSaveTeamMcpPluginCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
