<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<RootNamespace>MoAI.AIPlugin</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\infra\MoAI.Infra.Shared\MoAI.Infra.Shared.csproj" />
		<ProjectReference Include="..\MoAI.AIPlugin.Shared\MoAI.AIPlugin.Shared.csproj" />
		<ProjectReference Include="..\MoAI.AIPlugin.Api\MoAI.AIPlugin.Api.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Services\" />
		<Folder Include="Commands\" />
		<Folder Include="Queries\" />
	</ItemGroup>

</Project>
