/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createQueryAppDetailInfoCommandResponseFromDiscriminatorValue, type BusinessValidationResult, type QueryAppDetailInfoCommandResponse, UserType } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/app/manage/detail_info
 */
export interface Detail_infoRequestBuilder extends BaseRequestBuilder<Detail_infoRequestBuilder> {
    /**
     * 查询应用详细信息.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<QueryAppDetailInfoCommandResponse>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<Detail_infoRequestBuilderGetQueryParameters> | undefined) : Promise<QueryAppDetailInfoCommandResponse | undefined>;
    /**
     * 查询应用详细信息.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<Detail_infoRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * 查询应用详细信息.
 */
export interface Detail_infoRequestBuilderGetQueryParameters {
    /**
     * 应用id.
     */
    appId?: Guid;
    /**
     * 通过上下文自动配置id，前端不需要传递.
     */
    contextUserId?: number;
    /**
     * 通过上下文自动配置用户了偶像，前端不需要传递.
     */
    contextUserType?: UserType;
    /**
     * 团队id.
     */
    teamId?: number;
}
/**
 * Uri template for the request builder.
 */
export const Detail_infoRequestBuilderUriTemplate = "{+baseurl}/api/app/manage/detail_info{?AppId*,ContextUserId*,ContextUserType*,TeamId*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const Detail_infoRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "appId": "AppId",
    "contextUserId": "ContextUserId",
    "contextUserType": "ContextUserType",
    "teamId": "TeamId",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const Detail_infoRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: Detail_infoRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createQueryAppDetailInfoCommandResponseFromDiscriminatorValue,
        queryParametersMapper: Detail_infoRequestBuilderGetQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
