/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createExtractSkillPackageCommandResponseFromDiscriminatorValue, serializeExtractSkillPackageCommand, serializeExtractSkillPackageCommandResponse, type BusinessValidationResult, type ExtractSkillPackageCommand, type ExtractSkillPackageCommandResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/skill/file/extract
 */
export interface ExtractRequestBuilder extends BaseRequestBuilder<ExtractRequestBuilder> {
    /**
     * 解压技能压缩包：读取已上传的 zip，逐条目登记为技能包资源文件，并解析 SKILL.md 技能信息；登录用户可调用.
     * @param body 解压技能压缩包：读取已上传的 zip 文件，逐条目登记为技能包资源文件，并解析 SKILL.md 技能信息（frontmatter 名称/描述 + 正文使用说明）.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ExtractSkillPackageCommandResponse>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     post(body: ExtractSkillPackageCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ExtractSkillPackageCommandResponse | undefined>;
    /**
     * 解压技能压缩包：读取已上传的 zip，逐条目登记为技能包资源文件，并解析 SKILL.md 技能信息；登录用户可调用.
     * @param body 解压技能压缩包：读取已上传的 zip 文件，逐条目登记为技能包资源文件，并解析 SKILL.md 技能信息（frontmatter 名称/描述 + 正文使用说明）.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ExtractSkillPackageCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ExtractRequestBuilderUriTemplate = "{+baseurl}/api/skill/file/extract";
/**
 * Metadata for all the requests in the request builder.
 */
export const ExtractRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ExtractRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createExtractSkillPackageCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeExtractSkillPackageCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
