/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createQueryAppChatTopicListCommandResponseFromDiscriminatorValue, serializeQueryAppChatTopicListCommand, serializeQueryAppChatTopicListCommandResponse, type BusinessValidationResult, type QueryAppChatTopicListCommand, type QueryAppChatTopicListCommandResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/app/common/topic_list
 */
export interface Topic_listRequestBuilder extends BaseRequestBuilder<Topic_listRequestBuilder> {
    /**
     * 获取用户所有话题记录
     * @param body 查询用户在指定应用下的对话列表.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<QueryAppChatTopicListCommandResponse>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     post(body: QueryAppChatTopicListCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<QueryAppChatTopicListCommandResponse | undefined>;
    /**
     * 获取用户所有话题记录
     * @param body 查询用户在指定应用下的对话列表.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: QueryAppChatTopicListCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const Topic_listRequestBuilderUriTemplate = "{+baseurl}/api/app/common/topic_list";
/**
 * Metadata for all the requests in the request builder.
 */
export const Topic_listRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: Topic_listRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createQueryAppChatTopicListCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeQueryAppChatTopicListCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
