/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createQueryWikiDocumentListItemFromDiscriminatorValue, serializeQueryWikiDocumentInfoCommand, serializeQueryWikiDocumentListItem, type BusinessValidationResult, type QueryWikiDocumentInfoCommand, type QueryWikiDocumentListItem } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/wiki/document/document_info
 */
export interface Document_infoRequestBuilder extends BaseRequestBuilder<Document_infoRequestBuilder> {
    /**
     * 查询文档信息.
     * @param body 查询单个文档信息.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<QueryWikiDocumentListItem>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     post(body: QueryWikiDocumentInfoCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<QueryWikiDocumentListItem | undefined>;
    /**
     * 查询文档信息.
     * @param body 查询单个文档信息.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: QueryWikiDocumentInfoCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const Document_infoRequestBuilderUriTemplate = "{+baseurl}/api/wiki/document/document_info";
/**
 * Metadata for all the requests in the request builder.
 */
export const Document_infoRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: Document_infoRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createQueryWikiDocumentListItemFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeQueryWikiDocumentInfoCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
