/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { DynamicRequestBuilderRequestsMetadata, type DynamicRequestBuilder } from './dynamic/index.js';
// @ts-ignore
import { type WithPluginItemRequestBuilder, WithPluginItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { ListRequestBuilderRequestsMetadata, type ListRequestBuilder } from './list/index.js';
// @ts-ignore
import { McpRequestBuilderRequestsMetadata, type McpRequestBuilder } from './mcp/index.js';
// @ts-ignore
import { OpenapiRequestBuilderRequestsMetadata, type OpenapiRequestBuilder } from './openapi/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/team/{-id}/plugin
 */
export interface PluginRequestBuilder extends BaseRequestBuilder<PluginRequestBuilder> {
    /**
     * The dynamic property
     */
    get dynamic(): DynamicRequestBuilder;
    /**
     * The list property
     */
    get list(): ListRequestBuilder;
    /**
     * The mcp property
     */
    get mcp(): McpRequestBuilder;
    /**
     * The openapi property
     */
    get openapi(): OpenapiRequestBuilder;
    /**
     * Gets an item from the ApiSdk.api.team.item.plugin.item collection
     * @param pluginId 插件记录 id.
     * @returns {WithPluginItemRequestBuilder}
     */
     byPluginId(pluginId: Guid) : WithPluginItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const PluginRequestBuilderUriTemplate = "{+baseurl}/api/team/{%2Did}/plugin";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PluginRequestBuilderNavigationMetadata: Record<Exclude<keyof PluginRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byPluginId: {
        requestsMetadata: WithPluginItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["pluginId"],
    },
    dynamic: {
        requestsMetadata: DynamicRequestBuilderRequestsMetadata,
    },
    list: {
        requestsMetadata: ListRequestBuilderRequestsMetadata,
    },
    mcp: {
        requestsMetadata: McpRequestBuilderRequestsMetadata,
    },
    openapi: {
        requestsMetadata: OpenapiRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
