<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<RootNamespace>MoAI.AIPlugin.Dynamic</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\MoAI.AIPlugin.Shared\MoAI.AIPlugin.Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Plugins\" />
	</ItemGroup>

</Project>
