/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createQueryPaddleocrPluginListCommandResponseFromDiscriminatorValue, serializeQueryPaddleocrPluginListCommand, serializeQueryPaddleocrPluginListCommandResponse, type BusinessValidationResult, type QueryPaddleocrPluginListCommand, type QueryPaddleocrPluginListCommandResponse } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/wiki/plugin/paddleocr/plugin_list
 */
export interface Plugin_listRequestBuilder extends BaseRequestBuilder<Plugin_listRequestBuilder> {
    /**
     * 查询可用的飞桨 OCR 插件列表.
     * @param body 查询可用的飞桨 OCR 插件列表 (公开或被授权的 paddleocr_ocr、paddleocr_vl、paddleocr_structure_v3 插件).
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<QueryPaddleocrPluginListCommandResponse>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     post(body: QueryPaddleocrPluginListCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<QueryPaddleocrPluginListCommandResponse | undefined>;
    /**
     * 查询可用的飞桨 OCR 插件列表.
     * @param body 查询可用的飞桨 OCR 插件列表 (公开或被授权的 paddleocr_ocr、paddleocr_vl、paddleocr_structure_v3 插件).
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: QueryPaddleocrPluginListCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const Plugin_listRequestBuilderUriTemplate = "{+baseurl}/api/wiki/plugin/paddleocr/plugin_list";
/**
 * Metadata for all the requests in the request builder.
 */
export const Plugin_listRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: Plugin_listRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createQueryPaddleocrPluginListCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeQueryPaddleocrPluginListCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
