/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createPreUploadChatFileDocumentCommandResponseFromDiscriminatorValue, serializePreUploadChatFileDocumentCommand, serializePreUploadChatFileDocumentCommandResponse, type BusinessValidationResult, type PreUploadChatFileDocumentCommand, type PreUploadChatFileDocumentCommandResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/app/assistant/preupload_document
 */
export interface Preupload_documentRequestBuilder extends BaseRequestBuilder<Preupload_documentRequestBuilder> {
    /**
     * 预上传文档.
     * @param body 预上传对话文件.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PreUploadChatFileDocumentCommandResponse>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     post(body: PreUploadChatFileDocumentCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PreUploadChatFileDocumentCommandResponse | undefined>;
    /**
     * 预上传文档.
     * @param body 预上传对话文件.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: PreUploadChatFileDocumentCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const Preupload_documentRequestBuilderUriTemplate = "{+baseurl}/api/app/assistant/preupload_document";
/**
 * Metadata for all the requests in the request builder.
 */
export const Preupload_documentRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: Preupload_documentRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPreUploadChatFileDocumentCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializePreUploadChatFileDocumentCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
