/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createEmptyCommandResponseFromDiscriminatorValue, type BusinessValidationResult, type EmptyCommandResponse } from '../../../../models/index.js';
// @ts-ignore
import { MessagesRequestBuilderRequestsMetadata, type MessagesRequestBuilder } from './messages/index.js';
// @ts-ignore
import { PromptRequestBuilderRequestsMetadata, type PromptRequestBuilder } from './prompt/index.js';
// @ts-ignore
import { TitleRequestBuilderRequestsMetadata, type TitleRequestBuilder } from './title/index.js';
// @ts-ignore
import { ToolApprovalRequestBuilderRequestsMetadata, type ToolApprovalRequestBuilder } from './toolApproval/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/app/session/{sessionId}
 */
export interface WithSessionItemRequestBuilder extends BaseRequestBuilder<WithSessionItemRequestBuilder> {
    /**
     * The messages property
     */
    get messages(): MessagesRequestBuilder;
    /**
     * The prompt property
     */
    get prompt(): PromptRequestBuilder;
    /**
     * The title property
     */
    get title(): TitleRequestBuilder;
    /**
     * The toolApproval property
     */
    get toolApproval(): ToolApprovalRequestBuilder;
    /**
     * 删除会话（软删除，连同消息）；仅会话归属用户可操作.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<EmptyCommandResponse>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<EmptyCommandResponse | undefined>;
    /**
     * 删除会话（软删除，连同消息）；仅会话归属用户可操作.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithSessionItemRequestBuilderUriTemplate = "{+baseurl}/api/app/session/{sessionId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithSessionItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithSessionItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    messages: {
        requestsMetadata: MessagesRequestBuilderRequestsMetadata,
    },
    prompt: {
        requestsMetadata: PromptRequestBuilderRequestsMetadata,
    },
    title: {
        requestsMetadata: TitleRequestBuilderRequestsMetadata,
    },
    toolApproval: {
        requestsMetadata: ToolApprovalRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithSessionItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: WithSessionItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createEmptyCommandResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
