/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createQueryAllOAuthPrividerDetailCommandResponseFromDiscriminatorValue, type BusinessValidationResult, type QueryAllOAuthPrividerDetailCommandResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/admin/oauth/detail_list
 */
export interface Detail_listRequestBuilder extends BaseRequestBuilder<Detail_listRequestBuilder> {
    /**
     * 查询所有认证方式.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<QueryAllOAuthPrividerDetailCommandResponse>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<QueryAllOAuthPrividerDetailCommandResponse | undefined>;
    /**
     * 查询所有认证方式.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const Detail_listRequestBuilderUriTemplate = "{+baseurl}/api/admin/oauth/detail_list";
/**
 * Metadata for all the requests in the request builder.
 */
export const Detail_listRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: Detail_listRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createQueryAllOAuthPrividerDetailCommandResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
