<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<RootNamespace>MoAI.Team</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\database\MoAI.Database.Shared\MoAI.Database.Shared.csproj" />
		<ProjectReference Include="..\..\storage\MoAI.Storage.Shared\MoAI.Storage.Shared.csproj" />
		<ProjectReference Include="..\MoAI.Team.Api\MoAI.Team.Api.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Handlers\" />
		<Folder Include="Services\" />
	</ItemGroup>

</Project>
