/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createQueryWikiDocumentChunksCommandResponseFromDiscriminatorValue, serializeQueryWikiDocumentChunksCommand, serializeQueryWikiDocumentChunksCommandResponse, type BusinessValidationResult, type QueryWikiDocumentChunksCommand, type QueryWikiDocumentChunksCommandResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/wiki/document/get_chunks
 */
export interface Get_chunksRequestBuilder extends BaseRequestBuilder<Get_chunksRequestBuilder> {
    /**
     * 获取切割文档分片信息.
     * @param body 查询知识库文档被切割的块.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<QueryWikiDocumentChunksCommandResponse>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     post(body: QueryWikiDocumentChunksCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<QueryWikiDocumentChunksCommandResponse | undefined>;
    /**
     * 获取切割文档分片信息.
     * @param body 查询知识库文档被切割的块.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: QueryWikiDocumentChunksCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const Get_chunksRequestBuilderUriTemplate = "{+baseurl}/api/wiki/document/get_chunks";
/**
 * Metadata for all the requests in the request builder.
 */
export const Get_chunksRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: Get_chunksRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createQueryWikiDocumentChunksCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeQueryWikiDocumentChunksCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
