/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createQueryAccessAppsCommandResponseFromDiscriminatorValue, type BusinessValidationResult, type QueryAccessAppsCommandResponse, UserType } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/access-app/list
 */
export interface ListRequestBuilder extends BaseRequestBuilder<ListRequestBuilder> {
    /**
     * 查询团队下的应用接入列表，不回显 key 原文（仅前缀），需要团队 Admin 及以上角色.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<QueryAccessAppsCommandResponse>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<ListRequestBuilderGetQueryParameters> | undefined) : Promise<QueryAccessAppsCommandResponse | undefined>;
    /**
     * 查询团队下的应用接入列表，不回显 key 原文（仅前缀），需要团队 Admin 及以上角色.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<ListRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * 查询团队下的应用接入列表，不回显 key 原文（仅前缀），需要团队 Admin 及以上角色.
 */
export interface ListRequestBuilderGetQueryParameters {
    /**
     * 通过上下文自动配置id，前端不需要传递.
     */
    contextUserId?: string;
    /**
     * 通过上下文自动配置用户了偶像，前端不需要传递.
     */
    contextUserType?: UserType;
    /**
     * 团队 id.
     */
    teamId?: string;
}
/**
 * Uri template for the request builder.
 */
export const ListRequestBuilderUriTemplate = "{+baseurl}/api/access-app/list{?ContextUserId*,ContextUserType*,TeamId*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const ListRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "contextUserId": "ContextUserId",
    "contextUserType": "ContextUserType",
    "teamId": "TeamId",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ListRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ListRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createQueryAccessAppsCommandResponseFromDiscriminatorValue,
        queryParametersMapper: ListRequestBuilderGetQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
