/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AllRequestBuilderNavigationMetadata, type AllRequestBuilder } from './all/index.js';
// @ts-ignore
import { CommonRequestBuilderNavigationMetadata, type CommonRequestBuilder } from './common/index.js';
// @ts-ignore
import { InviteRequestBuilderRequestsMetadata, type InviteRequestBuilder } from './invite/index.js';
// @ts-ignore
import { MemberRequestBuilderNavigationMetadata, type MemberRequestBuilder } from './member/index.js';
// @ts-ignore
import { PluginRequestBuilderNavigationMetadata, type PluginRequestBuilder } from './plugin/index.js';
// @ts-ignore
import { TransferRequestBuilderRequestsMetadata, type TransferRequestBuilder } from './transfer/index.js';
// @ts-ignore
import { type UpdateRequestBuilder, UpdateRequestBuilderRequestsMetadata } from './update/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/team
 */
export interface TeamRequestBuilder extends BaseRequestBuilder<TeamRequestBuilder> {
    /**
     * The all property
     */
    get all(): AllRequestBuilder;
    /**
     * The common property
     */
    get common(): CommonRequestBuilder;
    /**
     * The invite property
     */
    get invite(): InviteRequestBuilder;
    /**
     * The member property
     */
    get member(): MemberRequestBuilder;
    /**
     * The plugin property
     */
    get plugin(): PluginRequestBuilder;
    /**
     * The transfer property
     */
    get transfer(): TransferRequestBuilder;
    /**
     * The update property
     */
    get update(): UpdateRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const TeamRequestBuilderUriTemplate = "{+baseurl}/api/team";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const TeamRequestBuilderNavigationMetadata: Record<Exclude<keyof TeamRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    all: {
        navigationMetadata: AllRequestBuilderNavigationMetadata,
    },
    common: {
        navigationMetadata: CommonRequestBuilderNavigationMetadata,
    },
    invite: {
        requestsMetadata: InviteRequestBuilderRequestsMetadata,
    },
    member: {
        navigationMetadata: MemberRequestBuilderNavigationMetadata,
    },
    plugin: {
        navigationMetadata: PluginRequestBuilderNavigationMetadata,
    },
    transfer: {
        requestsMetadata: TransferRequestBuilderRequestsMetadata,
    },
    update: {
        requestsMetadata: UpdateRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
