/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CrawlerRequestBuilderNavigationMetadata, type CrawlerRequestBuilder } from './crawler/index.js';
// @ts-ignore
import { Delete_configRequestBuilderRequestsMetadata, type Delete_configRequestBuilder } from './delete_config/index.js';
// @ts-ignore
import { FeishuRequestBuilderNavigationMetadata, type FeishuRequestBuilder } from './feishu/index.js';
// @ts-ignore
import { McpRequestBuilderNavigationMetadata, type McpRequestBuilder } from './mcp/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/wiki/plugin
 */
export interface PluginRequestBuilder extends BaseRequestBuilder<PluginRequestBuilder> {
    /**
     * The crawler property
     */
    get crawler(): CrawlerRequestBuilder;
    /**
     * The delete_config property
     */
    get delete_config(): Delete_configRequestBuilder;
    /**
     * The feishu property
     */
    get feishu(): FeishuRequestBuilder;
    /**
     * The mcp property
     */
    get mcp(): McpRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const PluginRequestBuilderUriTemplate = "{+baseurl}/api/wiki/plugin";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PluginRequestBuilderNavigationMetadata: Record<Exclude<keyof PluginRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    crawler: {
        navigationMetadata: CrawlerRequestBuilderNavigationMetadata,
    },
    delete_config: {
        requestsMetadata: Delete_configRequestBuilderRequestsMetadata,
    },
    feishu: {
        navigationMetadata: FeishuRequestBuilderNavigationMetadata,
    },
    mcp: {
        navigationMetadata: McpRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
