<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<RootNamespace>MoAI.Feishu</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Maomi.FeishuWss" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Http" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\account\MoAI.Account.Shared\MoAI.Account.Shared.csproj" />
		<ProjectReference Include="..\..\database\MoAI.Database.Shared\MoAI.Database.Shared.csproj" />
		<ProjectReference Include="..\..\infra\MoAI.Infra.Shared\MoAI.Infra.Shared.csproj" />
		<ProjectReference Include="..\..\team\MoAI.Team.Shared\MoAI.Team.Shared.csproj" />
		<ProjectReference Include="..\MoAI.Feishu.Api\MoAI.Feishu.Api.csproj" />
	</ItemGroup>

</Project>
