/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithTeamItemRequestBuilder, WithTeamItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/aigateway
 */
export interface AigatewayRequestBuilder extends BaseRequestBuilder<AigatewayRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.aigateway.item collection
     * @param teamId Unique identifier of the item
     * @returns {WithTeamItemRequestBuilder}
     */
     byTeamId(teamId: number) : WithTeamItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AigatewayRequestBuilderUriTemplate = "{+baseurl}/api/aigateway";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AigatewayRequestBuilderNavigationMetadata: Record<Exclude<keyof AigatewayRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byTeamId: {
        navigationMetadata: WithTeamItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["teamId"],
    },
};
/* tslint:enable */
/* eslint-enable */
