/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createSimpleIntFromDiscriminatorValue, serializeCreatePromptCommand, serializeSimpleInt, type BusinessValidationResult, type CreatePromptCommand, type SimpleInt } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/admin/prompt/create_prompt
 */
export interface Create_promptRequestBuilder extends BaseRequestBuilder<Create_promptRequestBuilder> {
    /**
     * 创建提示词.
     * @param body 创建提示词.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SimpleInt>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     post(body: CreatePromptCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SimpleInt | undefined>;
    /**
     * 创建提示词.
     * @param body 创建提示词.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreatePromptCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const Create_promptRequestBuilderUriTemplate = "{+baseurl}/api/admin/prompt/create_prompt";
/**
 * Metadata for all the requests in the request builder.
 */
export const Create_promptRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: Create_promptRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSimpleIntFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreatePromptCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
