/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createEmptyCommandResponseFromDiscriminatorValue, serializeDeleteDynamicPluginCommand, serializeEmptyCommandResponse, type BusinessValidationResult, type DeleteDynamicPluginCommand, type EmptyCommandResponse } from '../../../../models/index.js';
// @ts-ignore
import { SaveRequestBuilderRequestsMetadata, type SaveRequestBuilder } from './save/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/ai/plugin/dynamic
 */
export interface DynamicRequestBuilder extends BaseRequestBuilder<DynamicRequestBuilder> {
    /**
     * The save property
     */
    get save(): SaveRequestBuilder;
    /**
     * 删除动态插件实例.
     * @param body 删除动态插件实例.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<EmptyCommandResponse>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     delete(body: DeleteDynamicPluginCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<EmptyCommandResponse | undefined>;
    /**
     * 删除动态插件实例.
     * @param body 删除动态插件实例.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(body: DeleteDynamicPluginCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const DynamicRequestBuilderUriTemplate = "{+baseurl}/api/ai/plugin/dynamic";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const DynamicRequestBuilderNavigationMetadata: Record<Exclude<keyof DynamicRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    save: {
        requestsMetadata: SaveRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const DynamicRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: DynamicRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createEmptyCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeDeleteDynamicPluginCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
