/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { Builtin_function_listRequestBuilderRequestsMetadata, type Builtin_function_listRequestBuilder } from './builtin_function_list/index.js';
// @ts-ignore
import { Builtin_plugin_listRequestBuilderRequestsMetadata, type Builtin_plugin_listRequestBuilder } from './builtin_plugin_list/index.js';
// @ts-ignore
import { Delete_pluginRequestBuilderRequestsMetadata, type Delete_pluginRequestBuilder } from './delete_plugin/index.js';
// @ts-ignore
import { Function_listRequestBuilderRequestsMetadata, type Function_listRequestBuilder } from './function_list/index.js';
// @ts-ignore
import { Import_mcpRequestBuilderRequestsMetadata, type Import_mcpRequestBuilder } from './import_mcp/index.js';
// @ts-ignore
import { Import_openapiRequestBuilderRequestsMetadata, type Import_openapiRequestBuilder } from './import_openapi/index.js';
// @ts-ignore
import { Plugin_detailRequestBuilderRequestsMetadata, type Plugin_detailRequestBuilder } from './plugin_detail/index.js';
// @ts-ignore
import { Plugin_listRequestBuilderRequestsMetadata, type Plugin_listRequestBuilder } from './plugin_list/index.js';
// @ts-ignore
import { Pre_upload_openapiRequestBuilderRequestsMetadata, type Pre_upload_openapiRequestBuilder } from './pre_upload_openapi/index.js';
// @ts-ignore
import { Refresh_mcpRequestBuilderRequestsMetadata, type Refresh_mcpRequestBuilder } from './refresh_mcp/index.js';
// @ts-ignore
import { type Update_mcpRequestBuilder, Update_mcpRequestBuilderRequestsMetadata } from './update_mcp/index.js';
// @ts-ignore
import { type Update_openapiRequestBuilder, Update_openapiRequestBuilderRequestsMetadata } from './update_openapi/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/plugin
 */
export interface PluginRequestBuilder extends BaseRequestBuilder<PluginRequestBuilder> {
    /**
     * The builtin_function_list property
     */
    get builtin_function_list(): Builtin_function_listRequestBuilder;
    /**
     * The builtin_plugin_list property
     */
    get builtin_plugin_list(): Builtin_plugin_listRequestBuilder;
    /**
     * The delete_plugin property
     */
    get delete_plugin(): Delete_pluginRequestBuilder;
    /**
     * The function_list property
     */
    get function_list(): Function_listRequestBuilder;
    /**
     * The import_mcp property
     */
    get import_mcp(): Import_mcpRequestBuilder;
    /**
     * The import_openapi property
     */
    get import_openapi(): Import_openapiRequestBuilder;
    /**
     * The plugin_detail property
     */
    get plugin_detail(): Plugin_detailRequestBuilder;
    /**
     * The plugin_list property
     */
    get plugin_list(): Plugin_listRequestBuilder;
    /**
     * The pre_upload_openapi property
     */
    get pre_upload_openapi(): Pre_upload_openapiRequestBuilder;
    /**
     * The refresh_mcp property
     */
    get refresh_mcp(): Refresh_mcpRequestBuilder;
    /**
     * The update_mcp property
     */
    get update_mcp(): Update_mcpRequestBuilder;
    /**
     * The update_openapi property
     */
    get update_openapi(): Update_openapiRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const PluginRequestBuilderUriTemplate = "{+baseurl}/api/plugin";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PluginRequestBuilderNavigationMetadata: Record<Exclude<keyof PluginRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    builtin_function_list: {
        requestsMetadata: Builtin_function_listRequestBuilderRequestsMetadata,
    },
    builtin_plugin_list: {
        requestsMetadata: Builtin_plugin_listRequestBuilderRequestsMetadata,
    },
    delete_plugin: {
        requestsMetadata: Delete_pluginRequestBuilderRequestsMetadata,
    },
    function_list: {
        requestsMetadata: Function_listRequestBuilderRequestsMetadata,
    },
    import_mcp: {
        requestsMetadata: Import_mcpRequestBuilderRequestsMetadata,
    },
    import_openapi: {
        requestsMetadata: Import_openapiRequestBuilderRequestsMetadata,
    },
    plugin_detail: {
        requestsMetadata: Plugin_detailRequestBuilderRequestsMetadata,
    },
    plugin_list: {
        requestsMetadata: Plugin_listRequestBuilderRequestsMetadata,
    },
    pre_upload_openapi: {
        requestsMetadata: Pre_upload_openapiRequestBuilderRequestsMetadata,
    },
    refresh_mcp: {
        requestsMetadata: Refresh_mcpRequestBuilderRequestsMetadata,
    },
    update_mcp: {
        requestsMetadata: Update_mcpRequestBuilderRequestsMetadata,
    },
    update_openapi: {
        requestsMetadata: Update_openapiRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
