/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createEmptyCommandResponseFromDiscriminatorValue, serializeEmptyCommandResponse, serializeUpdateWorkflowDefinitionCommand, type BusinessValidationResult, type EmptyCommandResponse, type UpdateWorkflowDefinitionCommand } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/team/workflowapp/update
 */
export interface UpdateRequestBuilder extends BaseRequestBuilder<UpdateRequestBuilder> {
    /**
     * 更新工作流定义.更新现有工作流定义的配置信息，包括节点、连接和元数据.更新时会创建版本快照以维护历史记录.
     * @param body 更新工作流定义命令.用于更新工作流的基础信息和设计草稿.基础信息（Name、Description、Avatar）保存在 AppEntity 中.设计草稿保存在 AppWorkflowDesignEntity 的 UiDesignDraft 和 FunctionDesignDraft 字段中，不会影响已发布的版本.更新时会验证工作流定义的有效性（节点类型、连接等）.需要通过发布命令将草稿发布为正式版本.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<EmptyCommandResponse>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     put(body: UpdateWorkflowDefinitionCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<EmptyCommandResponse | undefined>;
    /**
     * 更新工作流定义.更新现有工作流定义的配置信息，包括节点、连接和元数据.更新时会创建版本快照以维护历史记录.
     * @param body 更新工作流定义命令.用于更新工作流的基础信息和设计草稿.基础信息（Name、Description、Avatar）保存在 AppEntity 中.设计草稿保存在 AppWorkflowDesignEntity 的 UiDesignDraft 和 FunctionDesignDraft 字段中，不会影响已发布的版本.更新时会验证工作流定义的有效性（节点类型、连接等）.需要通过发布命令将草稿发布为正式版本.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: UpdateWorkflowDefinitionCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const UpdateRequestBuilderUriTemplate = "{+baseurl}/api/team/workflowapp/update";
/**
 * Metadata for all the requests in the request builder.
 */
export const UpdateRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: UpdateRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createEmptyCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeUpdateWorkflowDefinitionCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
