/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { Complate_urlRequestBuilderRequestsMetadata, type Complate_urlRequestBuilder } from './complate_url/index.js';
// @ts-ignore
import { type UploadRequestBuilder, UploadRequestBuilderNavigationMetadata } from './upload/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/storage
 */
export interface StorageRequestBuilder extends BaseRequestBuilder<StorageRequestBuilder> {
    /**
     * The complate_url property
     */
    get complate_url(): Complate_urlRequestBuilder;
    /**
     * The upload property
     */
    get upload(): UploadRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const StorageRequestBuilderUriTemplate = "{+baseurl}/api/storage";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const StorageRequestBuilderNavigationMetadata: Record<Exclude<keyof StorageRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    complate_url: {
        requestsMetadata: Complate_urlRequestBuilderRequestsMetadata,
    },
    upload: {
        navigationMetadata: UploadRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
