/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ChatRequestBuilderNavigationMetadata, type ChatRequestBuilder } from './chat/index.js';
// @ts-ignore
import { MessagesRequestBuilderRequestsMetadata, type MessagesRequestBuilder } from './messages/index.js';
// @ts-ignore
import { ModelsRequestBuilderRequestsMetadata, type ModelsRequestBuilder } from './modelsRequests/index.js';
// @ts-ignore
import { ResponsesRequestBuilderRequestsMetadata, type ResponsesRequestBuilder } from './responses/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1
 */
export interface V1RequestBuilder extends BaseRequestBuilder<V1RequestBuilder> {
    /**
     * The chat property
     */
    get chat(): ChatRequestBuilder;
    /**
     * The messages property
     */
    get messages(): MessagesRequestBuilder;
    /**
     * The models property
     */
    get models(): ModelsRequestBuilder;
    /**
     * The responses property
     */
    get responses(): ResponsesRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const V1RequestBuilderUriTemplate = "{+baseurl}/v1";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const V1RequestBuilderNavigationMetadata: Record<Exclude<keyof V1RequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    chat: {
        navigationMetadata: ChatRequestBuilderNavigationMetadata,
    },
    messages: {
        requestsMetadata: MessagesRequestBuilderRequestsMetadata,
    },
    models: {
        requestsMetadata: ModelsRequestBuilderRequestsMetadata,
    },
    responses: {
        requestsMetadata: ResponsesRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
