/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ListRequestBuilderRequestsMetadata, type ListRequestBuilder } from './list/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/ai/plugin/manage
 */
export interface ManageRequestBuilder extends BaseRequestBuilder<ManageRequestBuilder> {
    /**
     * The list property
     */
    get list(): ListRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ManageRequestBuilderUriTemplate = "{+baseurl}/api/ai/plugin/manage";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ManageRequestBuilderNavigationMetadata: Record<Exclude<keyof ManageRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    list: {
        requestsMetadata: ListRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
