/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AuthorizeRequestBuilderRequestsMetadata, type AuthorizeRequestBuilder } from './authorize/index.js';
// @ts-ignore
import { RevokeRequestBuilderRequestsMetadata, type RevokeRequestBuilder } from './revoke/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/aimodel/authorization/team
 */
export interface TeamRequestBuilder extends BaseRequestBuilder<TeamRequestBuilder> {
    /**
     * The authorize property
     */
    get authorize(): AuthorizeRequestBuilder;
    /**
     * The revoke property
     */
    get revoke(): RevokeRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const TeamRequestBuilderUriTemplate = "{+baseurl}/api/aimodel/authorization/team";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const TeamRequestBuilderNavigationMetadata: Record<Exclude<keyof TeamRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    authorize: {
        requestsMetadata: AuthorizeRequestBuilderRequestsMetadata,
    },
    revoke: {
        requestsMetadata: RevokeRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
