/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ChatRequestBuilderRequestsMetadata, type ChatRequestBuilder } from './chat/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/agent
 */
export interface AgentRequestBuilder extends BaseRequestBuilder<AgentRequestBuilder> {
    /**
     * The chat property
     */
    get chat(): ChatRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AgentRequestBuilderUriTemplate = "{+baseurl}/api/agent";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AgentRequestBuilderNavigationMetadata: Record<Exclude<keyof AgentRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    chat: {
        requestsMetadata: ChatRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
