/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CompletionsRequestBuilderRequestsMetadata, type CompletionsRequestBuilder } from './completions/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/chat
 */
export interface ChatRequestBuilder extends BaseRequestBuilder<ChatRequestBuilder> {
    /**
     * The completions property
     */
    get completions(): CompletionsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ChatRequestBuilderUriTemplate = "{+baseurl}/v1/chat";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ChatRequestBuilderNavigationMetadata: Record<Exclude<keyof ChatRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    completions: {
        requestsMetadata: CompletionsRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
