/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createSimpleLongFromDiscriminatorValue, serializeCreateKnowledgeGraphRelationTypeCommand, serializeSimpleLong, type BusinessValidationResult, type CreateKnowledgeGraphRelationTypeCommand, type SimpleLong } from '../../../../models/index.js';
// @ts-ignore
import { type WithTypeItemRequestBuilder, WithTypeItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/knowledge-graph/{id}/relation-types
 */
export interface RelationTypesRequestBuilder extends BaseRequestBuilder<RelationTypesRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.knowledgeGraph.item.relationTypes.item collection
     * @param typeId 关系类型 id.
     * @returns {WithTypeItemRequestBuilder}
     */
     byTypeId(typeId: string) : WithTypeItemRequestBuilder;
    /**
     * 新增关系类型.
     * @param body 新增关系类型，需要团队 Admin 及以上角色.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SimpleLong>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     post(body: CreateKnowledgeGraphRelationTypeCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SimpleLong | undefined>;
    /**
     * 新增关系类型.
     * @param body 新增关系类型，需要团队 Admin 及以上角色.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateKnowledgeGraphRelationTypeCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const RelationTypesRequestBuilderUriTemplate = "{+baseurl}/api/knowledge-graph/{id}/relation-types";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const RelationTypesRequestBuilderNavigationMetadata: Record<Exclude<keyof RelationTypesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byTypeId: {
        requestsMetadata: WithTypeItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["typeId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const RelationTypesRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: RelationTypesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSimpleLongFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateKnowledgeGraphRelationTypeCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
