<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<RootNamespace>MoAI.Wiki</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\database\MoAI.Database.Shared\MoAI.Database.Shared.csproj" />
		<ProjectReference Include="..\..\team\MoAI.Team.Shared\MoAI.Team.Shared.csproj" />
		<ProjectReference Include="..\MoAI.Wiki.Api\MoAI.Wiki.Api.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Handlers\" />
	</ItemGroup>

</Project>
