/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createEmptyCommandResponseFromDiscriminatorValue, serializeEmptyCommandResponse, serializeUpdateKnowledgeGraphEmbeddingConfigCommand, type BusinessValidationResult, type EmptyCommandResponse, type UpdateKnowledgeGraphEmbeddingConfigCommand } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/knowledge-graph/{id}/embedding-config
 */
export interface EmbeddingConfigRequestBuilder extends BaseRequestBuilder<EmbeddingConfigRequestBuilder> {
    /**
     * 配置知识图谱向量化模型，仅托管图 Owner/Admin 可操作.
     * @param body 配置知识图谱的向量化模型与维度（管理员）；配置后图谱参与向量检索.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<EmptyCommandResponse>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     put(body: UpdateKnowledgeGraphEmbeddingConfigCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<EmptyCommandResponse | undefined>;
    /**
     * 配置知识图谱向量化模型，仅托管图 Owner/Admin 可操作.
     * @param body 配置知识图谱的向量化模型与维度（管理员）；配置后图谱参与向量检索.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: UpdateKnowledgeGraphEmbeddingConfigCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const EmbeddingConfigRequestBuilderUriTemplate = "{+baseurl}/api/knowledge-graph/{id}/embedding-config";
/**
 * Metadata for all the requests in the request builder.
 */
export const EmbeddingConfigRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: EmbeddingConfigRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createEmptyCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeUpdateKnowledgeGraphEmbeddingConfigCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
