/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createQueryUserBoundAccountsCommandResponseFromDiscriminatorValue, type BusinessValidationResult, type QueryUserBoundAccountsCommandResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/account/bound_accounts
 */
export interface Bound_accountsRequestBuilder extends BaseRequestBuilder<Bound_accountsRequestBuilder> {
    /**
     * 查询当前用户已经绑定的第三方账号.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<QueryUserBoundAccountsCommandResponse>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<QueryUserBoundAccountsCommandResponse | undefined>;
    /**
     * 查询当前用户已经绑定的第三方账号.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const Bound_accountsRequestBuilderUriTemplate = "{+baseurl}/api/account/bound_accounts";
/**
 * Metadata for all the requests in the request builder.
 */
export const Bound_accountsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: Bound_accountsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createQueryUserBoundAccountsCommandResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
