/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createQueryWikiConfigCommandResponseFromDiscriminatorValue, serializeQueryWikiConfigCommand, serializeQueryWikiConfigCommandResponse, type BusinessValidationResult, type QueryWikiConfigCommand, type QueryWikiConfigCommandResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/wiki/query_wiki_config
 */
export interface Query_wiki_configRequestBuilder extends BaseRequestBuilder<Query_wiki_configRequestBuilder> {
    /**
     * 查询知识库配置.
     * @param body 查询知识库设置信息.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<QueryWikiConfigCommandResponse>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     post(body: QueryWikiConfigCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<QueryWikiConfigCommandResponse | undefined>;
    /**
     * 查询知识库配置.
     * @param body 查询知识库设置信息.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: QueryWikiConfigCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const Query_wiki_configRequestBuilderUriTemplate = "{+baseurl}/api/wiki/query_wiki_config";
/**
 * Metadata for all the requests in the request builder.
 */
export const Query_wiki_configRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: Query_wiki_configRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createQueryWikiConfigCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeQueryWikiConfigCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
