/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createSyncAIModelCommandResponseFromDiscriminatorValue, serializeSyncAIModelCommand, serializeSyncAIModelCommandResponse, type BusinessValidationResult, type SyncAIModelCommand, type SyncAIModelCommandResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/ai/model/sync
 */
export interface SyncRequestBuilder extends BaseRequestBuilder<SyncRequestBuilder> {
    /**
     * 从供应商拉取模型列表并同步到数据库（仅管理员可访问）.
     * @param body 从供应商拉取并同步模型列表（后端负责获取模型并匹配内置 models.json）.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SyncAIModelCommandResponse>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     post(body: SyncAIModelCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SyncAIModelCommandResponse | undefined>;
    /**
     * 从供应商拉取模型列表并同步到数据库（仅管理员可访问）.
     * @param body 从供应商拉取并同步模型列表（后端负责获取模型并匹配内置 models.json）.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: SyncAIModelCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SyncRequestBuilderUriTemplate = "{+baseurl}/api/ai/model/sync";
/**
 * Metadata for all the requests in the request builder.
 */
export const SyncRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: SyncRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSyncAIModelCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSyncAIModelCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
