<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<RootNamespace>MoAI.TeamPlugin</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\database\MoAI.Database.Shared\MoAI.Database.Shared.csproj" />
		<ProjectReference Include="..\..\team\MoAI.Team.Shared\MoAI.Team.Shared.csproj" />
		<ProjectReference Include="..\..\aiplugin\MoAI.AIPlugin.Core\MoAI.AIPlugin.Core.csproj" />
		<ProjectReference Include="..\..\aiplugin\MoAI.AIPlugin.Custom\MoAI.AIPlugin.Custom.csproj" />
		<ProjectReference Include="..\MoAI.TeamPlugin.Api\MoAI.TeamPlugin.Api.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Handlers\" />
	</ItemGroup>

</Project>
