/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createEmptyCommandResponseFromDiscriminatorValue, serializeEmptyCommandResponse, serializeUpdateWikiEmbeddingCommand, type BusinessValidationResult, type EmptyCommandResponse, type UpdateWikiEmbeddingCommand } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/wiki/{-id}/embedding-config
 */
export interface EmbeddingConfigRequestBuilder extends BaseRequestBuilder<EmbeddingConfigRequestBuilder> {
    /**
     * 更新知识库向量化配置（向量化模型 + 维度，上限 2000），仅团队 Admin 及以上可操作.一旦 wiki 上已有文档被向量化（IsLock=true），该接口将返回 409.重排序模型不受该限制，见 UpdateWikiRerankModel.
     * @param body 更新知识库向量化模型与维度配置，需要团队 Admin 及以上角色.维度上限 2000：pgvector 在 2000 以内才能建 hnsw 索引.一旦该 wiki 已有文档被向量化（IsLock），模型与维度不可再修改.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<EmptyCommandResponse>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     put(body: UpdateWikiEmbeddingCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<EmptyCommandResponse | undefined>;
    /**
     * 更新知识库向量化配置（向量化模型 + 维度，上限 2000），仅团队 Admin 及以上可操作.一旦 wiki 上已有文档被向量化（IsLock=true），该接口将返回 409.重排序模型不受该限制，见 UpdateWikiRerankModel.
     * @param body 更新知识库向量化模型与维度配置，需要团队 Admin 及以上角色.维度上限 2000：pgvector 在 2000 以内才能建 hnsw 索引.一旦该 wiki 已有文档被向量化（IsLock），模型与维度不可再修改.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: UpdateWikiEmbeddingCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const EmbeddingConfigRequestBuilderUriTemplate = "{+baseurl}/api/wiki/{%2Did}/embedding-config";
/**
 * Metadata for all the requests in the request builder.
 */
export const EmbeddingConfigRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: EmbeddingConfigRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createEmptyCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeUpdateWikiEmbeddingCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
