/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createQueryInternalPluginListCommandResponseFromDiscriminatorValue, serializeQueryInternalPluginListCommand, serializeQueryInternalPluginListCommandResponse, type BusinessValidationResult, type QueryInternalPluginListCommand, type QueryInternalPluginListCommandResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/admin/plugin/internal_plugin_list
 */
export interface Internal_plugin_listRequestBuilder extends BaseRequestBuilder<Internal_plugin_listRequestBuilder> {
    /**
     * 查询内置插件简要信息列表.
     * @param body 查询内置插件列表.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<QueryInternalPluginListCommandResponse>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     post(body: QueryInternalPluginListCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<QueryInternalPluginListCommandResponse | undefined>;
    /**
     * 查询内置插件简要信息列表.
     * @param body 查询内置插件列表.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: QueryInternalPluginListCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const Internal_plugin_listRequestBuilderUriTemplate = "{+baseurl}/api/admin/plugin/internal_plugin_list";
/**
 * Metadata for all the requests in the request builder.
 */
export const Internal_plugin_listRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: Internal_plugin_listRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createQueryInternalPluginListCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeQueryInternalPluginListCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
