/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createExternalImportResponseFromDiscriminatorValue, serializeExternalImportResponse, serializeImportKnowledgeGraphJsonCommand, type BusinessValidationResult, type ExternalImportResponse, type ImportKnowledgeGraphJsonCommand } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/knowledge-graph/{id}/import-json
 */
export interface ImportJsonRequestBuilder extends BaseRequestBuilder<ImportJsonRequestBuilder> {
    /**
     * JSON 结构化导入（导入页）：直接反序列化导入页提交的 JSON 文本（顶层 mode/autoCreateTypes/validateOnly/nodes/edges）并落库，与外部 /import 共用管线（类型名引用可自动创建、业务 key 幂等 upsert、边端点按引用解析、逐条失败报告）；仅托管图 Admin+.
     * @param body JSON 结构化导入（内部导入页）：直接反序列化导入页提交的 JSON 文本并落库（与外部 /import 同一管线）；仅托管图 Admin+，返回逐条导入结果.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ExternalImportResponse>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     post(body: ImportKnowledgeGraphJsonCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ExternalImportResponse | undefined>;
    /**
     * JSON 结构化导入（导入页）：直接反序列化导入页提交的 JSON 文本（顶层 mode/autoCreateTypes/validateOnly/nodes/edges）并落库，与外部 /import 共用管线（类型名引用可自动创建、业务 key 幂等 upsert、边端点按引用解析、逐条失败报告）；仅托管图 Admin+.
     * @param body JSON 结构化导入（内部导入页）：直接反序列化导入页提交的 JSON 文本并落库（与外部 /import 同一管线）；仅托管图 Admin+，返回逐条导入结果.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ImportKnowledgeGraphJsonCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ImportJsonRequestBuilderUriTemplate = "{+baseurl}/api/knowledge-graph/{id}/import-json";
/**
 * Metadata for all the requests in the request builder.
 */
export const ImportJsonRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ImportJsonRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createExternalImportResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeImportKnowledgeGraphJsonCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
