/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createQueryTeamAuthorizationsCommandResponse2FromDiscriminatorValue, serializeQueryTeamAuthorizationsCommand2, serializeQueryTeamAuthorizationsCommandResponse2, type BusinessValidationResult, type QueryTeamAuthorizationsCommand2, type QueryTeamAuthorizationsCommandResponse2 } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/plugin/authorization/teams
 */
export interface TeamsRequestBuilder extends BaseRequestBuilder<TeamsRequestBuilder> {
    /**
     * 查询所有团队及其授权的插件列表.
     * @param body 查询所有团队及其授权的插件列表.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<QueryTeamAuthorizationsCommandResponse2>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     post(body: QueryTeamAuthorizationsCommand2, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<QueryTeamAuthorizationsCommandResponse2 | undefined>;
    /**
     * 查询所有团队及其授权的插件列表.
     * @param body 查询所有团队及其授权的插件列表.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: QueryTeamAuthorizationsCommand2, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const TeamsRequestBuilderUriTemplate = "{+baseurl}/api/plugin/authorization/teams";
/**
 * Metadata for all the requests in the request builder.
 */
export const TeamsRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: TeamsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createQueryTeamAuthorizationsCommandResponse2FromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeQueryTeamAuthorizationsCommand2,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
