/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AddRequestBuilderRequestsMetadata, type AddRequestBuilder } from './add/index.js';
// @ts-ignore
import { Delete_modelRequestBuilderRequestsMetadata, type Delete_modelRequestBuilder } from './delete_model/index.js';
// @ts-ignore
import { ProviderlistRequestBuilderRequestsMetadata, type ProviderlistRequestBuilder } from './providerlist/index.js';
// @ts-ignore
import { type TypeRequestBuilder, TypeRequestBuilderNavigationMetadata } from './type/index.js';
// @ts-ignore
import { type UpdateRequestBuilder, UpdateRequestBuilderRequestsMetadata } from './update/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/aimodel
 */
export interface AimodelRequestBuilder extends BaseRequestBuilder<AimodelRequestBuilder> {
    /**
     * The add property
     */
    get add(): AddRequestBuilder;
    /**
     * The delete_model property
     */
    get delete_model(): Delete_modelRequestBuilder;
    /**
     * The providerlist property
     */
    get providerlist(): ProviderlistRequestBuilder;
    /**
     * The type property
     */
    get type(): TypeRequestBuilder;
    /**
     * The update property
     */
    get update(): UpdateRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AimodelRequestBuilderUriTemplate = "{+baseurl}/api/aimodel";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AimodelRequestBuilderNavigationMetadata: Record<Exclude<keyof AimodelRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    add: {
        requestsMetadata: AddRequestBuilderRequestsMetadata,
    },
    delete_model: {
        requestsMetadata: Delete_modelRequestBuilderRequestsMetadata,
    },
    providerlist: {
        requestsMetadata: ProviderlistRequestBuilderRequestsMetadata,
    },
    type: {
        navigationMetadata: TypeRequestBuilderNavigationMetadata,
    },
    update: {
        requestsMetadata: UpdateRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
