/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { Public_modellistRequestBuilderRequestsMetadata, type Public_modellistRequestBuilder } from './public_modellist/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/aimodel
 */
export interface AimodelRequestBuilder extends BaseRequestBuilder<AimodelRequestBuilder> {
    /**
     * The public_modellist property
     */
    get public_modellist(): Public_modellistRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AimodelRequestBuilderUriTemplate = "{+baseurl}/api/aimodel";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AimodelRequestBuilderNavigationMetadata: Record<Exclude<keyof AimodelRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    public_modellist: {
        requestsMetadata: Public_modellistRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
