/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { Add_system_aimodelRequestBuilderRequestsMetadata, type Add_system_aimodelRequestBuilder } from './add_system_aimodel/index.js';
// @ts-ignore
import { Add_user_modelRequestBuilderRequestsMetadata, type Add_user_modelRequestBuilder } from './add_user_model/index.js';
// @ts-ignore
import { Delete_modelRequestBuilderRequestsMetadata, type Delete_modelRequestBuilder } from './delete_model/index.js';
// @ts-ignore
import { System_providerlistRequestBuilderRequestsMetadata, type System_providerlistRequestBuilder } from './system_providerlist/index.js';
// @ts-ignore
import { type TypeRequestBuilder, TypeRequestBuilderNavigationMetadata } from './type/index.js';
// @ts-ignore
import { type Update_system_aimodelRequestBuilder, Update_system_aimodelRequestBuilderRequestsMetadata } from './update_system_aimodel/index.js';
// @ts-ignore
import { type Update_user_aimodelRequestBuilder, Update_user_aimodelRequestBuilderRequestsMetadata } from './update_user_aimodel/index.js';
// @ts-ignore
import { type User_providerlistRequestBuilder, User_providerlistRequestBuilderRequestsMetadata } from './user_providerlist/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/aimodel
 */
export interface AimodelRequestBuilder extends BaseRequestBuilder<AimodelRequestBuilder> {
    /**
     * The add_system_aimodel property
     */
    get add_system_aimodel(): Add_system_aimodelRequestBuilder;
    /**
     * The add_user_model property
     */
    get add_user_model(): Add_user_modelRequestBuilder;
    /**
     * The delete_model property
     */
    get delete_model(): Delete_modelRequestBuilder;
    /**
     * The system_providerlist property
     */
    get system_providerlist(): System_providerlistRequestBuilder;
    /**
     * The type property
     */
    get type(): TypeRequestBuilder;
    /**
     * The update_system_aimodel property
     */
    get update_system_aimodel(): Update_system_aimodelRequestBuilder;
    /**
     * The update_user_aimodel property
     */
    get update_user_aimodel(): Update_user_aimodelRequestBuilder;
    /**
     * The user_providerlist property
     */
    get user_providerlist(): User_providerlistRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AimodelRequestBuilderUriTemplate = "{+baseurl}/api/aimodel";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AimodelRequestBuilderNavigationMetadata: Record<Exclude<keyof AimodelRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    add_system_aimodel: {
        requestsMetadata: Add_system_aimodelRequestBuilderRequestsMetadata,
    },
    add_user_model: {
        requestsMetadata: Add_user_modelRequestBuilderRequestsMetadata,
    },
    delete_model: {
        requestsMetadata: Delete_modelRequestBuilderRequestsMetadata,
    },
    system_providerlist: {
        requestsMetadata: System_providerlistRequestBuilderRequestsMetadata,
    },
    type: {
        navigationMetadata: TypeRequestBuilderNavigationMetadata,
    },
    update_system_aimodel: {
        requestsMetadata: Update_system_aimodelRequestBuilderRequestsMetadata,
    },
    update_user_aimodel: {
        requestsMetadata: Update_user_aimodelRequestBuilderRequestsMetadata,
    },
    user_providerlist: {
        requestsMetadata: User_providerlistRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
