/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createQuerySkillListCommandResponseFromDiscriminatorValue, type BusinessValidationResult, type QuerySkillListCommandResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/skill/market_list
 */
export interface Market_listRequestBuilder extends BaseRequestBuilder<Market_listRequestBuilder> {
    /**
     * 查询技能市场列表（已上架公开技能），所有登录用户可访问.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<QuerySkillListCommandResponse>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<Market_listRequestBuilderGetQueryParameters> | undefined) : Promise<QuerySkillListCommandResponse | undefined>;
    /**
     * 查询技能市场列表（已上架公开技能），所有登录用户可访问.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<Market_listRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * 查询技能市场列表（已上架公开技能），所有登录用户可访问.
 */
export interface Market_listRequestBuilderGetQueryParameters {
    /**
     * 按名称/标识/描述关键字筛选，空为不过滤.
     */
    keywords?: string;
}
/**
 * Uri template for the request builder.
 */
export const Market_listRequestBuilderUriTemplate = "{+baseurl}/api/skill/market_list{?Keywords*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const Market_listRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "keywords": "Keywords",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const Market_listRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: Market_listRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createQuerySkillListCommandResponseFromDiscriminatorValue,
        queryParametersMapper: Market_listRequestBuilderGetQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
