/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createQueryPluginListCommandResponseFromDiscriminatorValue, type BusinessValidationResult, type QueryPluginListCommandResponse } from '../../../models/index.js';
// @ts-ignore
import { CustomRequestBuilderNavigationMetadata, CustomRequestBuilderRequestsMetadata, type CustomRequestBuilder } from './custom/index.js';
// @ts-ignore
import { DynamicRequestBuilderNavigationMetadata, DynamicRequestBuilderRequestsMetadata, type DynamicRequestBuilder } from './dynamic/index.js';
// @ts-ignore
import { ManageRequestBuilderNavigationMetadata, type ManageRequestBuilder } from './manage/index.js';
// @ts-ignore
import { RunRequestBuilderRequestsMetadata, type RunRequestBuilder } from './run/index.js';
// @ts-ignore
import { StaticRequestBuilderNavigationMetadata, type StaticRequestBuilder } from './static/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/ai/plugin
 */
export interface PluginRequestBuilder extends BaseRequestBuilder<PluginRequestBuilder> {
    /**
     * The custom property
     */
    get custom(): CustomRequestBuilder;
    /**
     * The dynamic property
     */
    get dynamic(): DynamicRequestBuilder;
    /**
     * The manage property
     */
    get manage(): ManageRequestBuilder;
    /**
     * The run property
     */
    get run(): RunRequestBuilder;
    /**
     * The static property
     */
    get static(): StaticRequestBuilder;
    /**
     * 查询已发现插件列表（仅管理员）.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<QueryPluginListCommandResponse>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<QueryPluginListCommandResponse | undefined>;
    /**
     * 查询已发现插件列表（仅管理员）.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const PluginRequestBuilderUriTemplate = "{+baseurl}/api/ai/plugin";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PluginRequestBuilderNavigationMetadata: Record<Exclude<keyof PluginRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    custom: {
        requestsMetadata: CustomRequestBuilderRequestsMetadata,
        navigationMetadata: CustomRequestBuilderNavigationMetadata,
    },
    dynamic: {
        requestsMetadata: DynamicRequestBuilderRequestsMetadata,
        navigationMetadata: DynamicRequestBuilderNavigationMetadata,
    },
    manage: {
        navigationMetadata: ManageRequestBuilderNavigationMetadata,
    },
    run: {
        requestsMetadata: RunRequestBuilderRequestsMetadata,
    },
    static: {
        navigationMetadata: StaticRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const PluginRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: PluginRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createQueryPluginListCommandResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
