/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createQueryPromptListCommandResponseFromDiscriminatorValue, type BusinessValidationResult, type QueryPromptListCommandResponse, UserType } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/prompt/top_used
 */
export interface Top_usedRequestBuilder extends BaseRequestBuilder<Top_usedRequestBuilder> {
    /**
     * 查询使用次数最多的专家提示词（本人个人 + 指定团队范围，按使用次数倒序，默认前 10），供对话页输入框下方推荐展示；未绑定团队传入的提示词不在范围内.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<QueryPromptListCommandResponse>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<Top_usedRequestBuilderGetQueryParameters> | undefined) : Promise<QueryPromptListCommandResponse | undefined>;
    /**
     * 查询使用次数最多的专家提示词（本人个人 + 指定团队范围，按使用次数倒序，默认前 10），供对话页输入框下方推荐展示；未绑定团队传入的提示词不在范围内.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<Top_usedRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * 查询使用次数最多的专家提示词（本人个人 + 指定团队范围，按使用次数倒序，默认前 10），供对话页输入框下方推荐展示；未绑定团队传入的提示词不在范围内.
 */
export interface Top_usedRequestBuilderGetQueryParameters {
    /**
     * 通过上下文自动配置id，前端不需要传递.
     */
    contextUserId?: string;
    /**
     * 通过上下文自动配置用户了偶像，前端不需要传递.
     */
    contextUserType?: UserType;
    /**
     * 返回条数，默认且最大 10.
     */
    limit?: number;
    /**
     * 团队 id，团队提示词仅统计该团队.
     */
    teamId?: number;
}
/**
 * Uri template for the request builder.
 */
export const Top_usedRequestBuilderUriTemplate = "{+baseurl}/api/prompt/top_used{?ContextUserId*,ContextUserType*,Limit*,TeamId*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const Top_usedRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "contextUserId": "ContextUserId",
    "contextUserType": "ContextUserType",
    "limit": "Limit",
    "teamId": "TeamId",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const Top_usedRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: Top_usedRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createQueryPromptListCommandResponseFromDiscriminatorValue,
        queryParametersMapper: Top_usedRequestBuilderGetQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
