/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createQueryWikiCrawlerPageTasksCommandResponseFromDiscriminatorValue, type BusinessValidationResult, type QueryWikiCrawlerPageTasksCommandResponse } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/wiki/plugin/crawler/query_page_state
 */
export interface Query_page_stateRequestBuilder extends BaseRequestBuilder<Query_page_stateRequestBuilder> {
    /**
     * 查询爬虫正在爬取的每个页状态.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<QueryWikiCrawlerPageTasksCommandResponse>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<Query_page_stateRequestBuilderGetQueryParameters> | undefined) : Promise<QueryWikiCrawlerPageTasksCommandResponse | undefined>;
    /**
     * 查询爬虫正在爬取的每个页状态.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<Query_page_stateRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * 查询爬虫正在爬取的每个页状态.
 */
export interface Query_page_stateRequestBuilderGetQueryParameters {
    /**
     * id.
     */
    configId?: number;
    /**
     * 知识库id.
     */
    wikiId?: number;
}
/**
 * Uri template for the request builder.
 */
export const Query_page_stateRequestBuilderUriTemplate = "{+baseurl}/api/wiki/plugin/crawler/query_page_state?ConfigId={ConfigId}&WikiId={WikiId}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const Query_page_stateRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "configId": "ConfigId",
    "wikiId": "WikiId",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const Query_page_stateRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: Query_page_stateRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createQueryWikiCrawlerPageTasksCommandResponseFromDiscriminatorValue,
        queryParametersMapper: Query_page_stateRequestBuilderGetQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
