/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createQueryNativePluginTemplateListCommandResponseFromDiscriminatorValue, serializeQueryNativePluginTemplateListCommand, serializeQueryNativePluginTemplateListCommandResponse, type BusinessValidationResult, type QueryNativePluginTemplateListCommand, type QueryNativePluginTemplateListCommandResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/admin/native_plugin/template_list
 */
export interface Template_listRequestBuilder extends BaseRequestBuilder<Template_listRequestBuilder> {
    /**
     * 查询模板列表.
     * @param body 查询内置插件模板列表，包括原生插件和工具插件.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<QueryNativePluginTemplateListCommandResponse>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     post(body: QueryNativePluginTemplateListCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<QueryNativePluginTemplateListCommandResponse | undefined>;
    /**
     * 查询模板列表.
     * @param body 查询内置插件模板列表，包括原生插件和工具插件.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: QueryNativePluginTemplateListCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const Template_listRequestBuilderUriTemplate = "{+baseurl}/api/admin/native_plugin/template_list";
/**
 * Metadata for all the requests in the request builder.
 */
export const Template_listRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: Template_listRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createQueryNativePluginTemplateListCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeQueryNativePluginTemplateListCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
