<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<RootNamespace>MoAI.AIChannel</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\database\MoAI.Database.Shared\MoAI.Database.Shared.csproj" />
		<ProjectReference Include="..\MoAI.AIChannel.Api\MoAI.AIChannel.Api.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Commands\" />
		<Folder Include="Queries\" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Google.GenAI" />
	  <PackageReference Include="Microsoft.Agents.AI.Anthropic" />
	  <PackageReference Include="Microsoft.Agents.AI.OpenAI" />
	  <PackageReference Include="Mscc.GenerativeAI.Microsoft" />
	  <PackageReference Include="OllamaSharp" />
	</ItemGroup>

</Project>
