<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<RootNamespace>MoAI.AIPlugin.Custom</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ModelContextProtocol" />
		<PackageReference Include="Microsoft.OpenApi.Readers" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\account\MoAI.Account.Shared\MoAI.Account.Shared.csproj" />
		<ProjectReference Include="..\..\database\MoAI.Database.Shared\MoAI.Database.Shared.csproj" />
		<ProjectReference Include="..\..\classify\MoAI.Classify.Shared\MoAI.Classify.Shared.csproj" />
		<ProjectReference Include="..\..\infra\MoAI.Infra.Shared\MoAI.Infra.Shared.csproj" />
		<ProjectReference Include="..\..\storage\MoAI.Storage.Shared\MoAI.Storage.Shared.csproj" />
		<ProjectReference Include="..\MoAI.AIPlugin.Shared\MoAI.AIPlugin.Shared.csproj" />
		<ProjectReference Include="..\MoAI.AIPlugin.Core\MoAI.AIPlugin.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Services\" />
		<Folder Include="Commands\" />
		<Folder Include="Queries\" />
	</ItemGroup>

</Project>
