/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createQueryPublicSystemAiModelListCommandResponseFromDiscriminatorValue, serializeQueryPublicSystemAiModelListCommand, serializeQueryPublicSystemAiModelListCommandResponse, type BusinessValidationResult, type QueryPublicSystemAiModelListCommand, type QueryPublicSystemAiModelListCommandResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/aimodel/type/public_system_aimodel_list
 */
export interface Public_system_aimodel_listRequestBuilder extends BaseRequestBuilder<Public_system_aimodel_listRequestBuilder> {
    /**
     * 获取开放的系统 AI 模型列表.
     * @param body 查询公开访问的系统AI模型列表.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<QueryPublicSystemAiModelListCommandResponse>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     post(body: QueryPublicSystemAiModelListCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<QueryPublicSystemAiModelListCommandResponse | undefined>;
    /**
     * 获取开放的系统 AI 模型列表.
     * @param body 查询公开访问的系统AI模型列表.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: QueryPublicSystemAiModelListCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const Public_system_aimodel_listRequestBuilderUriTemplate = "{+baseurl}/api/aimodel/type/public_system_aimodel_list";
/**
 * Metadata for all the requests in the request builder.
 */
export const Public_system_aimodel_listRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: Public_system_aimodel_listRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createQueryPublicSystemAiModelListCommandResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeQueryPublicSystemAiModelListCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
