/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBusinessValidationResultFromDiscriminatorValue, createPluginRunResultFromDiscriminatorValue, serializePluginRunResult, serializeRunTeamPluginCommand, type BusinessValidationResult, type PluginRunResult, type RunTeamPluginCommand } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/team/{-id}/plugin/run
 */
export interface RunRequestBuilder extends BaseRequestBuilder<RunRequestBuilder> {
    /**
     * 执行团队可用插件，仅团队成员可访问.
     * @param body 执行团队可用插件（团队自有或已授权本团队的系统插件），仅团队成员可访问.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PluginRunResult>}
     * @throws {BusinessValidationResult} error when the service returns a 400 status code
     * @throws {BusinessValidationResult} error when the service returns a 401 status code
     * @throws {BusinessValidationResult} error when the service returns a 403 status code
     * @throws {BusinessValidationResult} error when the service returns a 409 status code
     * @throws {BusinessValidationResult} error when the service returns a 500 status code
     */
     post(body: RunTeamPluginCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PluginRunResult | undefined>;
    /**
     * 执行团队可用插件，仅团队成员可访问.
     * @param body 执行团队可用插件（团队自有或已授权本团队的系统插件），仅团队成员可访问.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: RunTeamPluginCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const RunRequestBuilderUriTemplate = "{+baseurl}/api/team/{%2Did}/plugin/run";
/**
 * Metadata for all the requests in the request builder.
 */
export const RunRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: RunRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBusinessValidationResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPluginRunResultFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeRunTeamPluginCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
