<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<RootNamespace>MoAI.KnowledgeGraph</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\database\MoAI.Database.Shared\MoAI.Database.Shared.csproj" />
		<ProjectReference Include="..\..\infra\MoAI.Infra.Configuration.Shared\MoAI.Infra.Configuration.csproj" />
		<ProjectReference Include="..\..\settings\MoAI.Settings.Shared\MoAI.Settings.Shared.csproj" />
		<ProjectReference Include="..\..\team\MoAI.Team.Shared\MoAI.Team.Shared.csproj" />
		<ProjectReference Include="..\MoAI.KnowledgeGraph.Api\MoAI.KnowledgeGraph.Api.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Neo4j.Driver" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Handlers\" />
		<Folder Include="Services\" />
	</ItemGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>MoAI.KnowledgeGraph.Tests</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>

</Project>
